package vega

// IsEvent methods needs to be implemented so we can used mapped types in GQL union.
func (Asset) IsEvent()                                                    {}
func (LiquidityProvision) IsEvent()                                       {}
func (Vote) IsEvent()                                                     {}
func (Order) IsEvent()                                                    {}
func (Account) IsEvent()                                                  {}
func (Trade) IsEvent()                                                    {}
func (Party) IsEvent()                                                    {}
func (MarginLevels) IsEvent()                                             {}
func (MarketData) IsEvent()                                               {}
func (GovernanceData) IsEvent()                                           {}
func (RiskFactor) IsEvent()                                               {}
func (Deposit) IsEvent()                                                  {}
func (Withdrawal) IsEvent()                                               {}
func (Market) IsEvent()                                                   {}
func (Future) IsProduct()                                                 {}
func (NewMarket) IsProposalChange()                                       {}
func (NewAsset) IsProposalChange()                                        {}
func (UpdateAsset) IsProposalChange()                                     {}
func (UpdateMarket) IsProposalChange()                                    {}
func (UpdateNetworkParameter) IsProposalChange()                          {}
func (NewFreeform) IsProposalChange()                                     {}
func (CancelTransfer) IsProposalChange()                                  {}
func (NewTransfer) IsProposalChange()                                     {}
func (UpdateMarketState) IsProposalChange()                               {}
func (NewSpotMarket) IsProposalChange()                                   {}
func (UpdateSpotMarket) IsProposalChange()                                {}
func (LogNormalRiskModel) IsRiskModel()                                   {}
func (SimpleRiskModel) IsRiskModel()                                      {}
func (SimpleModelParams) IsRiskModel()                                    {}
func (UpdateMarketConfiguration_Simple) IsUpdateMarketRiskParameters()    {}
func (UpdateMarketConfiguration_LogNormal) IsUpdateMarketRiskParameters() {}
func (DataSourceDefinitionInternal) IsDataSourceKind()                    {}
func (DataSourceDefinitionExternal) IsDataSourceKind()                    {}
func (DataSourceSpecConfiguration) IsExternalDataSourceKind()             {}
func (EthCallSpec) IsExternalDataSourceKind()                             {}
func (DataSourceSpecConfigurationTime) IsInternalDataSourceKind()         {}
func (OneOffTransfer) IsGovernanceTransferKind()                          {}
func (RecurringTransfer) IsGovernanceTransferKind()                       {}
func (FutureProduct) IsProductConfiguration()                             {}
func (SpotProduct) IsProductConfiguration()                               {}
func (PerpetualProduct) IsProductConfiguration()                          {}
func (Spot) IsProduct()                                                   {}
func (Perpetual) IsProduct()                                              {}
func (PerpetualData) IsProductData()                                      {}
func (UpdateFutureProduct) IsUpdateProductConfiguration()                 {}
func (UpdatePerpetualProduct) IsUpdateProductConfiguration()              {}
func (UpdateSpotMarketConfiguration_LogNormal) IsRiskModel()              {}
func (UpdateSpotMarketConfiguration_Simple) IsRiskModel()                 {}
func (NewSpotMarketConfiguration_Simple) IsRiskModel()                    {}
func (NewSpotMarketConfiguration_LogNormal) IsRiskModel()                 {}
func (DataSourceSpecConfigurationTimeTrigger) IsInternalDataSourceKind()  {}
