// Code generated by MockGen. DO NOT EDIT.
// Source: code.vegaprotocol.io/vega/plugins (interfaces: PosBuffer)

// Package mocks is a generated GoMock package.
package mocks

import (
	events "code.vegaprotocol.io/vega/events"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockPosBuffer is a mock of PosBuffer interface
type MockPosBuffer struct {
	ctrl     *gomock.Controller
	recorder *MockPosBufferMockRecorder
}

// MockPosBufferMockRecorder is the mock recorder for MockPosBuffer
type MockPosBufferMockRecorder struct {
	mock *MockPosBuffer
}

// NewMockPosBuffer creates a new mock instance
func NewMockPosBuffer(ctrl *gomock.Controller) *MockPosBuffer {
	mock := &MockPosBuffer{ctrl: ctrl}
	mock.recorder = &MockPosBufferMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockPosBuffer) EXPECT() *MockPosBufferMockRecorder {
	return m.recorder
}

// Subscribe mocks base method
func (m *MockPosBuffer) Subscribe() (<-chan []events.SettlePosition, int) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe")
	ret0, _ := ret[0].(<-chan []events.SettlePosition)
	ret1, _ := ret[1].(int)
	return ret0, ret1
}

// Subscribe indicates an expected call of Subscribe
func (mr *MockPosBufferMockRecorder) Subscribe() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockPosBuffer)(nil).Subscribe))
}

// Unsubscribe mocks base method
func (m *MockPosBuffer) Unsubscribe(arg0 int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Unsubscribe", arg0)
}

// Unsubscribe indicates an expected call of Unsubscribe
func (mr *MockPosBufferMockRecorder) Unsubscribe(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unsubscribe", reflect.TypeOf((*MockPosBuffer)(nil).Unsubscribe), arg0)
}
