-- +goose Up
CREATE INDEX ON accounts (tx_hash);
CREATE INDEX ON assets (tx_hash);
CREATE INDEX ON balances (tx_hash);
CREATE INDEX ON delegations (tx_hash);
CREATE INDEX ON deposits (tx_hash);
CREATE INDEX ON erc20_multisig_signer_events (tx_hash);
CREATE INDEX ON ethereum_key_rotations (tx_hash);
CREATE INDEX ON key_rotations (tx_hash);
CREATE INDEX ON ledger (tx_hash);
CREATE INDEX ON liquidity_provisions (tx_hash);
CREATE INDEX ON margin_levels (tx_hash);
CREATE INDEX ON markets (tx_hash);
CREATE INDEX ON network_parameters (tx_hash);
CREATE INDEX ON node_signatures (tx_hash);
CREATE INDEX ON nodes (tx_hash);
CREATE INDEX ON oracle_data (tx_hash);
CREATE INDEX ON oracle_specs (tx_hash);
CREATE INDEX ON orders (tx_hash);
CREATE INDEX ON parties (tx_hash);
CREATE INDEX ON positions (tx_hash);
CREATE INDEX ON proposals (tx_hash);
CREATE INDEX ON protocol_upgrade_proposals (tx_hash);
CREATE INDEX ON rewards (tx_hash);
CREATE INDEX ON trades (tx_hash);
CREATE INDEX ON transfers (tx_hash);
CREATE INDEX ON votes (tx_hash);
CREATE INDEX ON withdrawals (tx_hash);

-- +goose Down
DROP INDEX IF EXISTS accounts idx_tx_hash;
DROP INDEX IF EXISTS assets idx_tx_hash;
DROP INDEX IF EXISTS balances idx_tx_hash;
DROP INDEX IF EXISTS delegations idx_tx_hash;
DROP INDEX IF EXISTS deposits idx_tx_hash;
DROP INDEX IF EXISTS erc20_multisig_signer_events idx_tx_hash;
DROP INDEX IF EXISTS ethereum_key_rotations idx_tx_hash;
DROP INDEX IF EXISTS key_rotations idx_tx_hash;
DROP INDEX IF EXISTS ledger idx_tx_hash;
DROP INDEX IF EXISTS liquidity_provisions idx_tx_hash;
DROP INDEX IF EXISTS margin_levels idx_tx_hash;
DROP INDEX IF EXISTS markets idx_tx_hash;
DROP INDEX IF EXISTS network_parameters idx_tx_hash;
DROP INDEX IF EXISTS node_signatures idx_tx_hash;
DROP INDEX IF EXISTS nodes idx_tx_hash;
DROP INDEX IF EXISTS oracle_data idx_tx_hash;
DROP INDEX IF EXISTS oracle_specs idx_tx_hash;
DROP INDEX IF EXISTS orders idx_tx_hash;
DROP INDEX IF EXISTS parties idx_tx_hash;
DROP INDEX IF EXISTS positions idx_tx_hash;
DROP INDEX IF EXISTS proposals idx_tx_hash;
DROP INDEX IF EXISTS protocol_upgrade_proposals idx_tx_hash;
DROP INDEX IF EXISTS rewards idx_tx_hash;
DROP INDEX IF EXISTS trades idx_tx_hash;
DROP INDEX IF EXISTS transfers idx_tx_hash;
DROP INDEX IF EXISTS votes idx_tx_hash;
DROP INDEX IF EXISTS withdrawals idx_tx_hash;
