-- +goose Up

ALTER TYPE auction_trigger_type ADD VALUE 'AUCTION_TRIGGER_GOVERNANCE_SUSPENSION';
ALTER TYPE market_state_type ADD VALUE 'STATE_SUSPENDED_VIA_GOVERNANCE';
ALTER TYPE market_trading_mode_type ADD VALUE 'TRADING_MODE_SUSPENDED_VIA_GOVERNANCE';
ALTER TYPE proposal_error ADD VALUE 'PROPOSAL_ERROR_INVALID_MARKET_STATE_UPDATE';
