-- +goose Up

ALTER TYPE proposal_error ADD VALUE IF NOT EXISTS 'PROPOSAL_ERROR_INVALID_SIZE_DECIMAL_PLACES';

CREATE TYPE proposal_error_new AS ENUM('PROPOSAL_ERROR_UNSPECIFIED', 'PROPOSAL_ERROR_CLOSE_TIME_TOO_SOON', 'PROPOSAL_ERROR_CLOSE_TIME_TOO_LATE', 'PROPOSAL_ERROR_ENACT_TIME_TOO_SOON', 'PROPOSAL_ERROR_ENACT_TIME_TOO_LATE', 'PROPOSAL_ERROR_INSUFFICIENT_TOKENS', 'PROPOSAL_ERROR_INVALID_INSTRUMENT_SECURITY', 'PROPOSAL_ERROR_NO_PRODUCT', 'PROPOSAL_ERROR_UNSUPPORTED_PRODUCT', 'PROPOSAL_ERROR_NO_TRADING_MODE', 'PROPOSAL_ERROR_UNSUPPORTED_TRADING_MODE', 'PROPOSAL_ERROR_NODE_VALIDATION_FAILED', 'PROPOSAL_ERROR_MISSING_BUILTIN_ASSET_FIELD', 'PROPOSAL_ERROR_MISSING_ERC20_CONTRACT_ADDRESS', 'PROPOSAL_ERROR_INVALID_ASSET', 'PROPOSAL_ERROR_INCOMPATIBLE_TIMESTAMPS', 'PROPOSAL_ERROR_NO_RISK_PARAMETERS', 'PROPOSAL_ERROR_NETWORK_PARAMETER_INVALID_KEY', 'PROPOSAL_ERROR_NETWORK_PARAMETER_INVALID_VALUE', 'PROPOSAL_ERROR_NETWORK_PARAMETER_VALIDATION_FAILED', 'PROPOSAL_ERROR_OPENING_AUCTION_DURATION_TOO_SMALL', 'PROPOSAL_ERROR_OPENING_AUCTION_DURATION_TOO_LARGE', 'PROPOSAL_ERROR_MARKET_MISSING_LIQUIDITY_COMMITMENT', 'PROPOSAL_ERROR_COULD_NOT_INSTANTIATE_MARKET', 'PROPOSAL_ERROR_INVALID_FUTURE_PRODUCT', 'PROPOSAL_ERROR_MISSING_COMMITMENT_AMOUNT', 'PROPOSAL_ERROR_INVALID_FEE_AMOUNT', 'PROPOSAL_ERROR_INVALID_SHAPE', 'PROPOSAL_ERROR_INVALID_RISK_PARAMETER', 'PROPOSAL_ERROR_MAJORITY_THRESHOLD_NOT_REACHED', 'PROPOSAL_ERROR_PARTICIPATION_THRESHOLD_NOT_REACHED', 'PROPOSAL_ERROR_INVALID_ASSET_DETAILS', 'PROPOSAL_ERROR_UNKNOWN_TYPE', 'PROPOSAL_ERROR_UNKNOWN_RISK_PARAMETER_TYPE', 'PROPOSAL_ERROR_INVALID_FREEFORM', 'PROPOSAL_ERROR_INSUFFICIENT_EQUITY_LIKE_SHARE', 'PROPOSAL_ERROR_INVALID_MARKET', 'PROPOSAL_ERROR_TOO_MANY_MARKET_DECIMAL_PLACES', 'PROPOSAL_ERROR_TOO_MANY_PRICE_MONITORING_TRIGGERS', 'PROPOSAL_ERROR_ERC20_ADDRESS_ALREADY_IN_USE','PROPOSAL_ERROR_INVALID_SUCCESSOR_MARKET','PROPOSAL_ERROR_GOVERNANCE_TRANSFER_PROPOSAL_INVALID','PROPOSAL_ERROR_GOVERNANCE_TRANSFER_PROPOSAL_FAILED','PROPOSAL_ERROR_GOVERNANCE_CANCEL_TRANSFER_PROPOSAL_INVALID','PROPOSAL_ERROR_INVALID_MARKET_STATE_UPDATE','PROPOSAL_ERROR_MISSING_SLA_PARAMS','PROPOSAL_ERROR_INVALID_SLA_PARAMS','PROPOSAL_ERROR_INVALID_PERPETUAL_PRODUCT','PROPOSAL_ERROR_LP_PRICE_RANGE_NONPOSITIVE','PROPOSAL_ERROR_LP_PRICE_RANGE_TOO_LARGE','PROPOSAL_ERROR_LINEAR_SLIPPAGE_FACTOR_OUT_OF_RANGE','PROPOSAL_ERROR_QUADRATIC_SLIPPAGE_FACTOR_OUT_OF_RANGE','PROPOSAL_ERROR_INVALID_SPOT','PROPOSAL_ERROR_SPOT_PRODUCT_DISABLED','PROPOSAL_ERROR_INVALID_REFERRAL_PROGRAM','PROPOSAL_ERROR_INVALID_VOLUME_DISCOUNT_PROGRAM','PROPOSAL_ERROR_PROPOSAL_IN_BATCH_REJECTED','PROPOSAL_ERROR_PROPOSAL_IN_BATCH_DECLINED','PROPOSAL_ERROR_INVALID_SIZE_DECIMAL_PLACES');

DELETE FROM proposals WHERE reason = 'PROPOSAL_ERROR_INVALID_POSITION_DECIMAL_PLACES';

DROP VIEW IF EXISTS proposals_current;

ALTER TABLE proposals ALTER COLUMN reason TYPE proposal_error_new USING reason::text::proposal_error_new;

DROP TYPE proposal_error;

ALTER TYPE proposal_error_new RENAME TO proposal_error;

-- Recreate the proposals_current view
CREATE VIEW proposals_current AS (
    SELECT DISTINCT ON (id) * FROM proposals ORDER BY id, vega_time DESC
);

-- +goose Down

