-- +goose Up

ALTER TYPE auction_trigger_type ADD VALUE IF NOT EXISTS 'AUCTION_TRIGGER_PROTOCOL_AUTOMATED_PURCHASE';
ALTER TYPE market_trading_mode_type ADD VALUE IF NOT EXISTS 'TRADING_MODE_PROTOCOL_AUTOMATED_PURCHASE_AUCTION';
ALTER TYPE proposal_error ADD VALUE IF NOT EXISTS 'PROPOSAL_ERROR_INVALID_PROTOCOL_AUTOMATED_PURCHASE';
