// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/markets.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ContinuousTrading struct {
	TickSize             uint64   `protobuf:"varint,1,opt,name=tickSize,proto3" json:"tickSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContinuousTrading) Reset()         { *m = ContinuousTrading{} }
func (m *ContinuousTrading) String() string { return proto.CompactTextString(m) }
func (*ContinuousTrading) ProtoMessage()    {}
func (*ContinuousTrading) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef38c4b9a7594dbd, []int{0}
}

func (m *ContinuousTrading) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContinuousTrading.Unmarshal(m, b)
}
func (m *ContinuousTrading) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContinuousTrading.Marshal(b, m, deterministic)
}
func (m *ContinuousTrading) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContinuousTrading.Merge(m, src)
}
func (m *ContinuousTrading) XXX_Size() int {
	return xxx_messageInfo_ContinuousTrading.Size(m)
}
func (m *ContinuousTrading) XXX_DiscardUnknown() {
	xxx_messageInfo_ContinuousTrading.DiscardUnknown(m)
}

var xxx_messageInfo_ContinuousTrading proto.InternalMessageInfo

func (m *ContinuousTrading) GetTickSize() uint64 {
	if m != nil {
		return m.TickSize
	}
	return 0
}

type DiscreteTrading struct {
	Duration             int64    `protobuf:"varint,1,opt,name=duration,proto3" json:"duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiscreteTrading) Reset()         { *m = DiscreteTrading{} }
func (m *DiscreteTrading) String() string { return proto.CompactTextString(m) }
func (*DiscreteTrading) ProtoMessage()    {}
func (*DiscreteTrading) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef38c4b9a7594dbd, []int{1}
}

func (m *DiscreteTrading) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscreteTrading.Unmarshal(m, b)
}
func (m *DiscreteTrading) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscreteTrading.Marshal(b, m, deterministic)
}
func (m *DiscreteTrading) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscreteTrading.Merge(m, src)
}
func (m *DiscreteTrading) XXX_Size() int {
	return xxx_messageInfo_DiscreteTrading.Size(m)
}
func (m *DiscreteTrading) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscreteTrading.DiscardUnknown(m)
}

var xxx_messageInfo_DiscreteTrading proto.InternalMessageInfo

func (m *DiscreteTrading) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

type Future struct {
	Maturity string `protobuf:"bytes,1,opt,name=maturity,proto3" json:"maturity,omitempty"`
	Asset    string `protobuf:"bytes,2,opt,name=asset,proto3" json:"asset,omitempty"`
	// Types that are valid to be assigned to Oracle:
	//	*Future_EthereumEvent
	Oracle               isFuture_Oracle `protobuf_oneof:"oracle"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Future) Reset()         { *m = Future{} }
func (m *Future) String() string { return proto.CompactTextString(m) }
func (*Future) ProtoMessage()    {}
func (*Future) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef38c4b9a7594dbd, []int{2}
}

func (m *Future) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Future.Unmarshal(m, b)
}
func (m *Future) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Future.Marshal(b, m, deterministic)
}
func (m *Future) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Future.Merge(m, src)
}
func (m *Future) XXX_Size() int {
	return xxx_messageInfo_Future.Size(m)
}
func (m *Future) XXX_DiscardUnknown() {
	xxx_messageInfo_Future.DiscardUnknown(m)
}

var xxx_messageInfo_Future proto.InternalMessageInfo

func (m *Future) GetMaturity() string {
	if m != nil {
		return m.Maturity
	}
	return ""
}

func (m *Future) GetAsset() string {
	if m != nil {
		return m.Asset
	}
	return ""
}

type isFuture_Oracle interface {
	isFuture_Oracle()
}

type Future_EthereumEvent struct {
	EthereumEvent *EthereumEvent `protobuf:"bytes,100,opt,name=ethereumEvent,proto3,oneof"`
}

func (*Future_EthereumEvent) isFuture_Oracle() {}

func (m *Future) GetOracle() isFuture_Oracle {
	if m != nil {
		return m.Oracle
	}
	return nil
}

func (m *Future) GetEthereumEvent() *EthereumEvent {
	if x, ok := m.GetOracle().(*Future_EthereumEvent); ok {
		return x.EthereumEvent
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Future) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Future_EthereumEvent)(nil),
	}
}

type EthereumEvent struct {
	ContractID           string   `protobuf:"bytes,1,opt,name=contractID,proto3" json:"contractID,omitempty"`
	Event                string   `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EthereumEvent) Reset()         { *m = EthereumEvent{} }
func (m *EthereumEvent) String() string { return proto.CompactTextString(m) }
func (*EthereumEvent) ProtoMessage()    {}
func (*EthereumEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef38c4b9a7594dbd, []int{3}
}

func (m *EthereumEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EthereumEvent.Unmarshal(m, b)
}
func (m *EthereumEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EthereumEvent.Marshal(b, m, deterministic)
}
func (m *EthereumEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EthereumEvent.Merge(m, src)
}
func (m *EthereumEvent) XXX_Size() int {
	return xxx_messageInfo_EthereumEvent.Size(m)
}
func (m *EthereumEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_EthereumEvent.DiscardUnknown(m)
}

var xxx_messageInfo_EthereumEvent proto.InternalMessageInfo

func (m *EthereumEvent) GetContractID() string {
	if m != nil {
		return m.ContractID
	}
	return ""
}

func (m *EthereumEvent) GetEvent() string {
	if m != nil {
		return m.Event
	}
	return ""
}

type InstrumentMetadata struct {
	Tags                 []string `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstrumentMetadata) Reset()         { *m = InstrumentMetadata{} }
func (m *InstrumentMetadata) String() string { return proto.CompactTextString(m) }
func (*InstrumentMetadata) ProtoMessage()    {}
func (*InstrumentMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef38c4b9a7594dbd, []int{4}
}

func (m *InstrumentMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstrumentMetadata.Unmarshal(m, b)
}
func (m *InstrumentMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstrumentMetadata.Marshal(b, m, deterministic)
}
func (m *InstrumentMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstrumentMetadata.Merge(m, src)
}
func (m *InstrumentMetadata) XXX_Size() int {
	return xxx_messageInfo_InstrumentMetadata.Size(m)
}
func (m *InstrumentMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_InstrumentMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_InstrumentMetadata proto.InternalMessageInfo

func (m *InstrumentMetadata) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type Instrument struct {
	Id       string              `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code     string              `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name     string              `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Metadata *InstrumentMetadata `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Types that are valid to be assigned to Product:
	//	*Instrument_Future
	Product              isInstrument_Product `protobuf_oneof:"product"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Instrument) Reset()         { *m = Instrument{} }
func (m *Instrument) String() string { return proto.CompactTextString(m) }
func (*Instrument) ProtoMessage()    {}
func (*Instrument) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef38c4b9a7594dbd, []int{5}
}

func (m *Instrument) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Instrument.Unmarshal(m, b)
}
func (m *Instrument) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Instrument.Marshal(b, m, deterministic)
}
func (m *Instrument) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Instrument.Merge(m, src)
}
func (m *Instrument) XXX_Size() int {
	return xxx_messageInfo_Instrument.Size(m)
}
func (m *Instrument) XXX_DiscardUnknown() {
	xxx_messageInfo_Instrument.DiscardUnknown(m)
}

var xxx_messageInfo_Instrument proto.InternalMessageInfo

func (m *Instrument) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Instrument) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Instrument) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Instrument) GetMetadata() *InstrumentMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type isInstrument_Product interface {
	isInstrument_Product()
}

type Instrument_Future struct {
	Future *Future `protobuf:"bytes,100,opt,name=future,proto3,oneof"`
}

func (*Instrument_Future) isInstrument_Product() {}

func (m *Instrument) GetProduct() isInstrument_Product {
	if m != nil {
		return m.Product
	}
	return nil
}

func (m *Instrument) GetFuture() *Future {
	if x, ok := m.GetProduct().(*Instrument_Future); ok {
		return x.Future
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Instrument) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Instrument_Future)(nil),
	}
}

type BuiltinFutures struct {
	HistoricVolatility   float64  `protobuf:"fixed64,1,opt,name=historicVolatility,proto3" json:"historicVolatility,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuiltinFutures) Reset()         { *m = BuiltinFutures{} }
func (m *BuiltinFutures) String() string { return proto.CompactTextString(m) }
func (*BuiltinFutures) ProtoMessage()    {}
func (*BuiltinFutures) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef38c4b9a7594dbd, []int{6}
}

func (m *BuiltinFutures) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuiltinFutures.Unmarshal(m, b)
}
func (m *BuiltinFutures) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuiltinFutures.Marshal(b, m, deterministic)
}
func (m *BuiltinFutures) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuiltinFutures.Merge(m, src)
}
func (m *BuiltinFutures) XXX_Size() int {
	return xxx_messageInfo_BuiltinFutures.Size(m)
}
func (m *BuiltinFutures) XXX_DiscardUnknown() {
	xxx_messageInfo_BuiltinFutures.DiscardUnknown(m)
}

var xxx_messageInfo_BuiltinFutures proto.InternalMessageInfo

func (m *BuiltinFutures) GetHistoricVolatility() float64 {
	if m != nil {
		return m.HistoricVolatility
	}
	return 0
}

type ExternalRiskModel struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Config               map[string]string `protobuf:"bytes,2,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ExternalRiskModel) Reset()         { *m = ExternalRiskModel{} }
func (m *ExternalRiskModel) String() string { return proto.CompactTextString(m) }
func (*ExternalRiskModel) ProtoMessage()    {}
func (*ExternalRiskModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef38c4b9a7594dbd, []int{7}
}

func (m *ExternalRiskModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExternalRiskModel.Unmarshal(m, b)
}
func (m *ExternalRiskModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExternalRiskModel.Marshal(b, m, deterministic)
}
func (m *ExternalRiskModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExternalRiskModel.Merge(m, src)
}
func (m *ExternalRiskModel) XXX_Size() int {
	return xxx_messageInfo_ExternalRiskModel.Size(m)
}
func (m *ExternalRiskModel) XXX_DiscardUnknown() {
	xxx_messageInfo_ExternalRiskModel.DiscardUnknown(m)
}

var xxx_messageInfo_ExternalRiskModel proto.InternalMessageInfo

func (m *ExternalRiskModel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ExternalRiskModel) GetConfig() map[string]string {
	if m != nil {
		return m.Config
	}
	return nil
}

type TradableInstrument struct {
	Instrument *Instrument `protobuf:"bytes,1,opt,name=instrument,proto3" json:"instrument,omitempty"`
	// Types that are valid to be assigned to RiskModel:
	//	*TradableInstrument_BuiltinFutures
	//	*TradableInstrument_ExternalRiskModel
	RiskModel            isTradableInstrument_RiskModel `protobuf_oneof:"riskModel"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *TradableInstrument) Reset()         { *m = TradableInstrument{} }
func (m *TradableInstrument) String() string { return proto.CompactTextString(m) }
func (*TradableInstrument) ProtoMessage()    {}
func (*TradableInstrument) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef38c4b9a7594dbd, []int{8}
}

func (m *TradableInstrument) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TradableInstrument.Unmarshal(m, b)
}
func (m *TradableInstrument) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TradableInstrument.Marshal(b, m, deterministic)
}
func (m *TradableInstrument) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TradableInstrument.Merge(m, src)
}
func (m *TradableInstrument) XXX_Size() int {
	return xxx_messageInfo_TradableInstrument.Size(m)
}
func (m *TradableInstrument) XXX_DiscardUnknown() {
	xxx_messageInfo_TradableInstrument.DiscardUnknown(m)
}

var xxx_messageInfo_TradableInstrument proto.InternalMessageInfo

func (m *TradableInstrument) GetInstrument() *Instrument {
	if m != nil {
		return m.Instrument
	}
	return nil
}

type isTradableInstrument_RiskModel interface {
	isTradableInstrument_RiskModel()
}

type TradableInstrument_BuiltinFutures struct {
	BuiltinFutures *BuiltinFutures `protobuf:"bytes,100,opt,name=builtinFutures,proto3,oneof"`
}

type TradableInstrument_ExternalRiskModel struct {
	ExternalRiskModel *ExternalRiskModel `protobuf:"bytes,101,opt,name=externalRiskModel,proto3,oneof"`
}

func (*TradableInstrument_BuiltinFutures) isTradableInstrument_RiskModel() {}

func (*TradableInstrument_ExternalRiskModel) isTradableInstrument_RiskModel() {}

func (m *TradableInstrument) GetRiskModel() isTradableInstrument_RiskModel {
	if m != nil {
		return m.RiskModel
	}
	return nil
}

func (m *TradableInstrument) GetBuiltinFutures() *BuiltinFutures {
	if x, ok := m.GetRiskModel().(*TradableInstrument_BuiltinFutures); ok {
		return x.BuiltinFutures
	}
	return nil
}

func (m *TradableInstrument) GetExternalRiskModel() *ExternalRiskModel {
	if x, ok := m.GetRiskModel().(*TradableInstrument_ExternalRiskModel); ok {
		return x.ExternalRiskModel
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*TradableInstrument) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*TradableInstrument_BuiltinFutures)(nil),
		(*TradableInstrument_ExternalRiskModel)(nil),
	}
}

type Market struct {
	Id                 string              `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TradableInstrument *TradableInstrument `protobuf:"bytes,2,opt,name=tradableInstrument,proto3" json:"tradableInstrument,omitempty"`
	DecimalPlaces      uint64              `protobuf:"varint,3,opt,name=decimalPlaces,proto3" json:"decimalPlaces,omitempty"`
	// Types that are valid to be assigned to TradingMode:
	//	*Market_Continuous
	//	*Market_Discrete
	TradingMode          isMarket_TradingMode `protobuf_oneof:"tradingMode"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Market) Reset()         { *m = Market{} }
func (m *Market) String() string { return proto.CompactTextString(m) }
func (*Market) ProtoMessage()    {}
func (*Market) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef38c4b9a7594dbd, []int{9}
}

func (m *Market) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Market.Unmarshal(m, b)
}
func (m *Market) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Market.Marshal(b, m, deterministic)
}
func (m *Market) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Market.Merge(m, src)
}
func (m *Market) XXX_Size() int {
	return xxx_messageInfo_Market.Size(m)
}
func (m *Market) XXX_DiscardUnknown() {
	xxx_messageInfo_Market.DiscardUnknown(m)
}

var xxx_messageInfo_Market proto.InternalMessageInfo

func (m *Market) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Market) GetTradableInstrument() *TradableInstrument {
	if m != nil {
		return m.TradableInstrument
	}
	return nil
}

func (m *Market) GetDecimalPlaces() uint64 {
	if m != nil {
		return m.DecimalPlaces
	}
	return 0
}

type isMarket_TradingMode interface {
	isMarket_TradingMode()
}

type Market_Continuous struct {
	Continuous *ContinuousTrading `protobuf:"bytes,100,opt,name=continuous,proto3,oneof"`
}

type Market_Discrete struct {
	Discrete *DiscreteTrading `protobuf:"bytes,101,opt,name=discrete,proto3,oneof"`
}

func (*Market_Continuous) isMarket_TradingMode() {}

func (*Market_Discrete) isMarket_TradingMode() {}

func (m *Market) GetTradingMode() isMarket_TradingMode {
	if m != nil {
		return m.TradingMode
	}
	return nil
}

func (m *Market) GetContinuous() *ContinuousTrading {
	if x, ok := m.GetTradingMode().(*Market_Continuous); ok {
		return x.Continuous
	}
	return nil
}

func (m *Market) GetDiscrete() *DiscreteTrading {
	if x, ok := m.GetTradingMode().(*Market_Discrete); ok {
		return x.Discrete
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Market) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Market_Continuous)(nil),
		(*Market_Discrete)(nil),
	}
}

func init() {
	proto.RegisterType((*ContinuousTrading)(nil), "vega.ContinuousTrading")
	proto.RegisterType((*DiscreteTrading)(nil), "vega.DiscreteTrading")
	proto.RegisterType((*Future)(nil), "vega.Future")
	proto.RegisterType((*EthereumEvent)(nil), "vega.EthereumEvent")
	proto.RegisterType((*InstrumentMetadata)(nil), "vega.InstrumentMetadata")
	proto.RegisterType((*Instrument)(nil), "vega.Instrument")
	proto.RegisterType((*BuiltinFutures)(nil), "vega.BuiltinFutures")
	proto.RegisterType((*ExternalRiskModel)(nil), "vega.ExternalRiskModel")
	proto.RegisterMapType((map[string]string)(nil), "vega.ExternalRiskModel.ConfigEntry")
	proto.RegisterType((*TradableInstrument)(nil), "vega.TradableInstrument")
	proto.RegisterType((*Market)(nil), "vega.Market")
}

func init() { proto.RegisterFile("proto/markets.proto", fileDescriptor_ef38c4b9a7594dbd) }

var fileDescriptor_ef38c4b9a7594dbd = []byte{
	// 634 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x54, 0xc1, 0x6e, 0xd3, 0x4c,
	0x10, 0x8e, 0x93, 0xfc, 0xf9, 0x93, 0xc9, 0x9f, 0xfe, 0xed, 0xb6, 0x08, 0xab, 0x07, 0x08, 0x06,
	0xa1, 0x5c, 0x48, 0x50, 0xcb, 0x81, 0x52, 0x09, 0xa1, 0xb4, 0x01, 0xf7, 0x50, 0x09, 0x2d, 0x88,
	0x03, 0xb7, 0xad, 0x3d, 0x4d, 0x57, 0xb1, 0x77, 0xab, 0xf5, 0xb8, 0xa2, 0xdc, 0x38, 0xf1, 0x18,
	0x3c, 0x01, 0x6f, 0xc4, 0xc3, 0x20, 0xaf, 0x37, 0xc6, 0x49, 0xca, 0xc9, 0xfb, 0xcd, 0x7e, 0x9f,
	0x77, 0xe7, 0x9b, 0xd9, 0x81, 0xdd, 0x6b, 0xa3, 0x49, 0x4f, 0x52, 0x61, 0x16, 0x48, 0xd9, 0xd8,
	0x22, 0xd6, 0xbe, 0xc1, 0xb9, 0x08, 0x26, 0xb0, 0x73, 0xa2, 0x15, 0x49, 0x95, 0xeb, 0x3c, 0xfb,
	0x68, 0x44, 0x2c, 0xd5, 0x9c, 0xed, 0x43, 0x97, 0x64, 0xb4, 0xf8, 0x20, 0xbf, 0xa2, 0xef, 0x0d,
	0xbd, 0x51, 0x9b, 0x57, 0x38, 0x78, 0x06, 0xff, 0x9f, 0xca, 0x2c, 0x32, 0x48, 0x58, 0xa3, 0xc7,
	0xb9, 0x11, 0x24, 0xb5, 0xb2, 0xf4, 0x16, 0xaf, 0x70, 0xf0, 0xcd, 0x83, 0xce, 0xdb, 0x9c, 0x72,
	0x83, 0x05, 0x2d, 0x15, 0x94, 0x1b, 0x49, 0xb7, 0x96, 0xd6, 0xe3, 0x15, 0x66, 0x7b, 0xf0, 0x8f,
	0xc8, 0x32, 0x24, 0xbf, 0x69, 0x37, 0x4a, 0xc0, 0x8e, 0x61, 0x80, 0x74, 0x85, 0x06, 0xf3, 0x74,
	0x76, 0x83, 0x8a, 0xfc, 0x78, 0xe8, 0x8d, 0xfa, 0x07, 0xbb, 0xe3, 0xe2, 0xea, 0xe3, 0x59, 0x7d,
	0x2b, 0x6c, 0xf0, 0x55, 0xee, 0xb4, 0x0b, 0x1d, 0x6d, 0x44, 0x94, 0x60, 0x30, 0x83, 0xc1, 0x0a,
	0x97, 0x3d, 0x00, 0x88, 0xb4, 0x22, 0x23, 0x22, 0x3a, 0x3b, 0x75, 0x77, 0xa9, 0x45, 0x8a, 0xdb,
	0xa0, 0x3d, 0xcf, 0xdd, 0xc6, 0x82, 0x60, 0x04, 0xec, 0x4c, 0x65, 0x64, 0xf2, 0x14, 0x15, 0x9d,
	0x23, 0x89, 0x58, 0x90, 0x60, 0x0c, 0xda, 0x24, 0xe6, 0x99, 0xef, 0x0d, 0x5b, 0xa3, 0x1e, 0xb7,
	0xeb, 0xe0, 0xa7, 0x07, 0xf0, 0x87, 0xca, 0xb6, 0xa0, 0x29, 0x63, 0x77, 0x4c, 0x53, 0xc6, 0x85,
	0x24, 0xd2, 0x31, 0xba, 0xbf, 0xdb, 0x75, 0x11, 0x53, 0x22, 0x45, 0xbf, 0x55, 0xc6, 0x8a, 0x35,
	0x7b, 0x01, 0xdd, 0xd4, 0x1d, 0xe3, 0xb7, 0x6d, 0xe6, 0x7e, 0x99, 0xf9, 0xe6, 0x35, 0x78, 0xc5,
	0x64, 0x4f, 0xa1, 0x73, 0x69, 0x0d, 0x77, 0x6e, 0xfd, 0x57, 0x6a, 0xca, 0x22, 0x84, 0x0d, 0xee,
	0x76, 0xa7, 0x3d, 0xf8, 0xf7, 0xda, 0xe8, 0x38, 0x8f, 0x28, 0x78, 0x03, 0x5b, 0xd3, 0x5c, 0x26,
	0x24, 0x55, 0xc9, 0xca, 0xd8, 0x18, 0xd8, 0x95, 0xcc, 0x48, 0x1b, 0x19, 0x7d, 0xd2, 0x89, 0x20,
	0x99, 0x2c, 0xab, 0xe6, 0xf1, 0x3b, 0x76, 0x82, 0x1f, 0x1e, 0xec, 0xcc, 0xbe, 0x10, 0x1a, 0x25,
	0x12, 0x2e, 0xb3, 0xc5, 0xb9, 0x8e, 0x31, 0xa9, 0x92, 0xf2, 0x6a, 0x49, 0x1d, 0x43, 0x27, 0xd2,
	0xea, 0x52, 0xce, 0xfd, 0xe6, 0xb0, 0x35, 0xea, 0x1f, 0x3c, 0x76, 0xc5, 0x5c, 0x17, 0x8f, 0x4f,
	0x2c, 0x6b, 0xa6, 0xc8, 0xdc, 0x72, 0x27, 0xd9, 0x3f, 0x82, 0x7e, 0x2d, 0xcc, 0xb6, 0xa1, 0xb5,
	0xc0, 0x65, 0x33, 0x15, 0xcb, 0xa2, 0x72, 0x37, 0x22, 0xc9, 0x97, 0xde, 0x96, 0xe0, 0x55, 0xf3,
	0xa5, 0x17, 0xfc, 0xf2, 0x80, 0x15, 0x0d, 0x2b, 0x2e, 0x12, 0xac, 0xd5, 0xe6, 0x39, 0x80, 0xac,
	0x90, 0xfd, 0x53, 0xff, 0x60, 0x7b, 0xdd, 0x65, 0x5e, 0xe3, 0xb0, 0xd7, 0xb0, 0x75, 0xb1, 0x62,
	0x96, 0xf3, 0x79, 0xaf, 0x54, 0xad, 0x1a, 0x19, 0x36, 0xf8, 0x1a, 0x9b, 0xbd, 0x83, 0x1d, 0x5c,
	0x4f, 0xd6, 0x47, 0xfb, 0x8b, 0xfb, 0x7f, 0xf1, 0x22, 0x6c, 0xf0, 0x4d, 0xcd, 0xb4, 0x0f, 0x3d,
	0xb3, 0x04, 0xc1, 0xf7, 0x26, 0x74, 0xce, 0xed, 0xfb, 0xde, 0x68, 0xb7, 0x10, 0x18, 0x6d, 0x24,
	0x6e, 0x0d, 0xaa, 0x1a, 0x6a, 0xd3, 0x18, 0x7e, 0x87, 0x86, 0x3d, 0x81, 0x41, 0x8c, 0x91, 0x4c,
	0x45, 0xf2, 0x3e, 0x11, 0x11, 0x66, 0xb6, 0x5b, 0xdb, 0x7c, 0x35, 0xc8, 0x8e, 0xca, 0xd7, 0x55,
	0x8e, 0x14, 0x67, 0x8e, 0xcb, 0x6c, 0x63, 0xd4, 0x84, 0x0d, 0x5e, 0x23, 0xb3, 0x43, 0xe8, 0xc6,
	0x6e, 0xb8, 0x38, 0x4b, 0xee, 0x95, 0xc2, 0xb5, 0x91, 0x13, 0x36, 0x78, 0x45, 0x9c, 0x0e, 0xa0,
	0x4f, 0x65, 0xb8, 0xb0, 0x62, 0xfa, 0xe8, 0xf3, 0xc3, 0xe2, 0x45, 0x59, 0x9d, 0x9d, 0x74, 0x91,
	0x4e, 0xc6, 0x52, 0x4f, 0x0a, 0x3c, 0xb1, 0x81, 0x8b, 0x8e, 0xfd, 0x1c, 0xfe, 0x0e, 0x00, 0x00,
	0xff, 0xff, 0x5c, 0x99, 0xc5, 0xf6, 0x18, 0x05, 0x00, 0x00,
}
