// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/vega.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Side int32

const (
	Side_Buy  Side = 0
	Side_Sell Side = 1
)

var Side_name = map[int32]string{
	0: "Buy",
	1: "Sell",
}

var Side_value = map[string]int32{
	"Buy":  0,
	"Sell": 1,
}

func (x Side) String() string {
	return proto.EnumName(Side_name, int32(x))
}

func (Side) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bb6b8173ee11af27, []int{0}
}

type Interval int32

const (
	Interval_I1M  Interval = 0
	Interval_I5M  Interval = 1
	Interval_I15M Interval = 2
	Interval_I1H  Interval = 3
	Interval_I6H  Interval = 4
	Interval_I1D  Interval = 5
)

var Interval_name = map[int32]string{
	0: "I1M",
	1: "I5M",
	2: "I15M",
	3: "I1H",
	4: "I6H",
	5: "I1D",
}

var Interval_value = map[string]int32{
	"I1M":  0,
	"I5M":  1,
	"I15M": 2,
	"I1H":  3,
	"I6H":  4,
	"I1D":  5,
}

func (x Interval) String() string {
	return proto.EnumName(Interval_name, int32(x))
}

func (Interval) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bb6b8173ee11af27, []int{1}
}

type OrderError int32

const (
	OrderError_NONE                        OrderError = 0
	OrderError_INVALID_MARKET_ID           OrderError = 1
	OrderError_INVALID_ORDER_ID            OrderError = 2
	OrderError_ORDER_OUT_OF_SEQUENCE       OrderError = 3
	OrderError_INVALID_REMAINING_SIZE      OrderError = 4
	OrderError_TIME_FAILURE                OrderError = 5
	OrderError_ORDER_REMOVAL_FAILURE       OrderError = 6
	OrderError_INVALID_EXPIRATION_DATETIME OrderError = 7
	OrderError_INVALID_ORDER_REFERENCE     OrderError = 8
	OrderError_EDIT_NOT_ALLOWED            OrderError = 9
	OrderError_ORDER_AMEND_FAILURE         OrderError = 10
	OrderError_ORDER_NOT_FOUND             OrderError = 11
)

var OrderError_name = map[int32]string{
	0:  "NONE",
	1:  "INVALID_MARKET_ID",
	2:  "INVALID_ORDER_ID",
	3:  "ORDER_OUT_OF_SEQUENCE",
	4:  "INVALID_REMAINING_SIZE",
	5:  "TIME_FAILURE",
	6:  "ORDER_REMOVAL_FAILURE",
	7:  "INVALID_EXPIRATION_DATETIME",
	8:  "INVALID_ORDER_REFERENCE",
	9:  "EDIT_NOT_ALLOWED",
	10: "ORDER_AMEND_FAILURE",
	11: "ORDER_NOT_FOUND",
}

var OrderError_value = map[string]int32{
	"NONE":                        0,
	"INVALID_MARKET_ID":           1,
	"INVALID_ORDER_ID":            2,
	"ORDER_OUT_OF_SEQUENCE":       3,
	"INVALID_REMAINING_SIZE":      4,
	"TIME_FAILURE":                5,
	"ORDER_REMOVAL_FAILURE":       6,
	"INVALID_EXPIRATION_DATETIME": 7,
	"INVALID_ORDER_REFERENCE":     8,
	"EDIT_NOT_ALLOWED":            9,
	"ORDER_AMEND_FAILURE":         10,
	"ORDER_NOT_FOUND":             11,
}

func (x OrderError) String() string {
	return proto.EnumName(OrderError_name, int32(x))
}

func (OrderError) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bb6b8173ee11af27, []int{2}
}

type ChainStatus int32

const (
	ChainStatus_DISCONNECTED ChainStatus = 0
	ChainStatus_REPLAYING    ChainStatus = 1
	ChainStatus_CONNECTED    ChainStatus = 2
)

var ChainStatus_name = map[int32]string{
	0: "DISCONNECTED",
	1: "REPLAYING",
	2: "CONNECTED",
}

var ChainStatus_value = map[string]int32{
	"DISCONNECTED": 0,
	"REPLAYING":    1,
	"CONNECTED":    2,
}

func (x ChainStatus) String() string {
	return proto.EnumName(ChainStatus_name, int32(x))
}

func (ChainStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bb6b8173ee11af27, []int{3}
}

type AccountType int32

const (
	AccountType_INSURANCE  AccountType = 0
	AccountType_SETTLEMENT AccountType = 1
	AccountType_MARGIN     AccountType = 2
	AccountType_MARKET     AccountType = 3
	AccountType_GENERAL    AccountType = 4
)

var AccountType_name = map[int32]string{
	0: "INSURANCE",
	1: "SETTLEMENT",
	2: "MARGIN",
	3: "MARKET",
	4: "GENERAL",
}

var AccountType_value = map[string]int32{
	"INSURANCE":  0,
	"SETTLEMENT": 1,
	"MARGIN":     2,
	"MARKET":     3,
	"GENERAL":    4,
}

func (x AccountType) String() string {
	return proto.EnumName(AccountType_name, int32(x))
}

func (AccountType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bb6b8173ee11af27, []int{4}
}

type SettleType int32

const (
	SettleType_LOSS SettleType = 0
	SettleType_WIN  SettleType = 1
)

var SettleType_name = map[int32]string{
	0: "LOSS",
	1: "WIN",
}

var SettleType_value = map[string]int32{
	"LOSS": 0,
	"WIN":  1,
}

func (x SettleType) String() string {
	return proto.EnumName(SettleType_name, int32(x))
}

func (SettleType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bb6b8173ee11af27, []int{5}
}

type Order_Type int32

const (
	Order_GTC Order_Type = 0
	Order_GTT Order_Type = 1
	Order_ENE Order_Type = 2
	Order_FOK Order_Type = 3
)

var Order_Type_name = map[int32]string{
	0: "GTC",
	1: "GTT",
	2: "ENE",
	3: "FOK",
}

var Order_Type_value = map[string]int32{
	"GTC": 0,
	"GTT": 1,
	"ENE": 2,
	"FOK": 3,
}

func (x Order_Type) String() string {
	return proto.EnumName(Order_Type_name, int32(x))
}

func (Order_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bb6b8173ee11af27, []int{4, 0}
}

type Order_Status int32

const (
	Order_Active    Order_Status = 0
	Order_Expired   Order_Status = 1
	Order_Cancelled Order_Status = 2
	Order_Stopped   Order_Status = 3
	Order_Filled    Order_Status = 4
)

var Order_Status_name = map[int32]string{
	0: "Active",
	1: "Expired",
	2: "Cancelled",
	3: "Stopped",
	4: "Filled",
}

var Order_Status_value = map[string]int32{
	"Active":    0,
	"Expired":   1,
	"Cancelled": 2,
	"Stopped":   3,
	"Filled":    4,
}

func (x Order_Status) String() string {
	return proto.EnumName(Order_Status_name, int32(x))
}

func (Order_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bb6b8173ee11af27, []int{4, 1}
}

type Amount struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Amount) Reset()         { *m = Amount{} }
func (m *Amount) String() string { return proto.CompactTextString(m) }
func (*Amount) ProtoMessage()    {}
func (*Amount) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb6b8173ee11af27, []int{0}
}

func (m *Amount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Amount.Unmarshal(m, b)
}
func (m *Amount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Amount.Marshal(b, m, deterministic)
}
func (m *Amount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Amount.Merge(m, src)
}
func (m *Amount) XXX_Size() int {
	return xxx_messageInfo_Amount.Size(m)
}
func (m *Amount) XXX_DiscardUnknown() {
	xxx_messageInfo_Amount.DiscardUnknown(m)
}

var xxx_messageInfo_Amount proto.InternalMessageInfo

func (m *Amount) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Party struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Positions            []*MarketPosition `protobuf:"bytes,2,rep,name=positions,proto3" json:"positions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Party) Reset()         { *m = Party{} }
func (m *Party) String() string { return proto.CompactTextString(m) }
func (*Party) ProtoMessage()    {}
func (*Party) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb6b8173ee11af27, []int{1}
}

func (m *Party) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Party.Unmarshal(m, b)
}
func (m *Party) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Party.Marshal(b, m, deterministic)
}
func (m *Party) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Party.Merge(m, src)
}
func (m *Party) XXX_Size() int {
	return xxx_messageInfo_Party.Size(m)
}
func (m *Party) XXX_DiscardUnknown() {
	xxx_messageInfo_Party.DiscardUnknown(m)
}

var xxx_messageInfo_Party proto.InternalMessageInfo

func (m *Party) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Party) GetPositions() []*MarketPosition {
	if m != nil {
		return m.Positions
	}
	return nil
}

type RiskFactor struct {
	Market               string   `protobuf:"bytes,1,opt,name=market,proto3" json:"market,omitempty"`
	Short                float64  `protobuf:"fixed64,2,opt,name=short,proto3" json:"short,omitempty"`
	Long                 float64  `protobuf:"fixed64,3,opt,name=long,proto3" json:"long,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RiskFactor) Reset()         { *m = RiskFactor{} }
func (m *RiskFactor) String() string { return proto.CompactTextString(m) }
func (*RiskFactor) ProtoMessage()    {}
func (*RiskFactor) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb6b8173ee11af27, []int{2}
}

func (m *RiskFactor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RiskFactor.Unmarshal(m, b)
}
func (m *RiskFactor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RiskFactor.Marshal(b, m, deterministic)
}
func (m *RiskFactor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RiskFactor.Merge(m, src)
}
func (m *RiskFactor) XXX_Size() int {
	return xxx_messageInfo_RiskFactor.Size(m)
}
func (m *RiskFactor) XXX_DiscardUnknown() {
	xxx_messageInfo_RiskFactor.DiscardUnknown(m)
}

var xxx_messageInfo_RiskFactor proto.InternalMessageInfo

func (m *RiskFactor) GetMarket() string {
	if m != nil {
		return m.Market
	}
	return ""
}

func (m *RiskFactor) GetShort() float64 {
	if m != nil {
		return m.Short
	}
	return 0
}

func (m *RiskFactor) GetLong() float64 {
	if m != nil {
		return m.Long
	}
	return 0
}

type RiskResult struct {
	// timestamp when these risk factors were generated
	UpdatedTimestamp int64 `protobuf:"varint,1,opt,name=updatedTimestamp,proto3" json:"updatedTimestamp,omitempty"`
	// risk factors (long and short) for each marginable asset/currency (usualy == settlement assets) in the market
	RiskFactors map[string]*RiskFactor `protobuf:"bytes,2,rep,name=riskFactors,proto3" json:"riskFactors,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// time when risk factors are expected to change (or empty if risk factors are continually updated)
	NextUpdateTimestamp int64 `protobuf:"varint,3,opt,name=nextUpdateTimestamp,proto3" json:"nextUpdateTimestamp,omitempty"`
	// predicted risk factors at next change (what they'd be if the change occurred now)
	PredictedNextRiskFactors map[string]*RiskFactor `protobuf:"bytes,4,rep,name=predictedNextRiskFactors,proto3" json:"predictedNextRiskFactors,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral     struct{}               `json:"-"`
	XXX_unrecognized         []byte                 `json:"-"`
	XXX_sizecache            int32                  `json:"-"`
}

func (m *RiskResult) Reset()         { *m = RiskResult{} }
func (m *RiskResult) String() string { return proto.CompactTextString(m) }
func (*RiskResult) ProtoMessage()    {}
func (*RiskResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb6b8173ee11af27, []int{3}
}

func (m *RiskResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RiskResult.Unmarshal(m, b)
}
func (m *RiskResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RiskResult.Marshal(b, m, deterministic)
}
func (m *RiskResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RiskResult.Merge(m, src)
}
func (m *RiskResult) XXX_Size() int {
	return xxx_messageInfo_RiskResult.Size(m)
}
func (m *RiskResult) XXX_DiscardUnknown() {
	xxx_messageInfo_RiskResult.DiscardUnknown(m)
}

var xxx_messageInfo_RiskResult proto.InternalMessageInfo

func (m *RiskResult) GetUpdatedTimestamp() int64 {
	if m != nil {
		return m.UpdatedTimestamp
	}
	return 0
}

func (m *RiskResult) GetRiskFactors() map[string]*RiskFactor {
	if m != nil {
		return m.RiskFactors
	}
	return nil
}

func (m *RiskResult) GetNextUpdateTimestamp() int64 {
	if m != nil {
		return m.NextUpdateTimestamp
	}
	return 0
}

func (m *RiskResult) GetPredictedNextRiskFactors() map[string]*RiskFactor {
	if m != nil {
		return m.PredictedNextRiskFactors
	}
	return nil
}

type Order struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Market               string       `protobuf:"bytes,2,opt,name=market,proto3" json:"market,omitempty"`
	Party                string       `protobuf:"bytes,3,opt,name=party,proto3" json:"party,omitempty"`
	Side                 Side         `protobuf:"varint,4,opt,name=side,proto3,enum=vega.Side" json:"side,omitempty"`
	Price                uint64       `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	Size                 uint64       `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
	Remaining            uint64       `protobuf:"varint,7,opt,name=remaining,proto3" json:"remaining,omitempty"`
	Type                 Order_Type   `protobuf:"varint,8,opt,name=type,proto3,enum=vega.Order_Type" json:"type,omitempty"`
	CreatedAt            int64        `protobuf:"varint,9,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	Status               Order_Status `protobuf:"varint,10,opt,name=status,proto3,enum=vega.Order_Status" json:"status,omitempty"`
	ExpiresAt            int64        `protobuf:"varint,11,opt,name=expiresAt,proto3" json:"expiresAt,omitempty"`
	Reference            string       `protobuf:"bytes,12,opt,name=reference,proto3" json:"reference,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb6b8173ee11af27, []int{4}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Order) GetMarket() string {
	if m != nil {
		return m.Market
	}
	return ""
}

func (m *Order) GetParty() string {
	if m != nil {
		return m.Party
	}
	return ""
}

func (m *Order) GetSide() Side {
	if m != nil {
		return m.Side
	}
	return Side_Buy
}

func (m *Order) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Order) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Order) GetRemaining() uint64 {
	if m != nil {
		return m.Remaining
	}
	return 0
}

func (m *Order) GetType() Order_Type {
	if m != nil {
		return m.Type
	}
	return Order_GTC
}

func (m *Order) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Order) GetStatus() Order_Status {
	if m != nil {
		return m.Status
	}
	return Order_Active
}

func (m *Order) GetExpiresAt() int64 {
	if m != nil {
		return m.ExpiresAt
	}
	return 0
}

func (m *Order) GetReference() string {
	if m != nil {
		return m.Reference
	}
	return ""
}

type OrderCancellationConfirmation struct {
	Order                *Order   `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderCancellationConfirmation) Reset()         { *m = OrderCancellationConfirmation{} }
func (m *OrderCancellationConfirmation) String() string { return proto.CompactTextString(m) }
func (*OrderCancellationConfirmation) ProtoMessage()    {}
func (*OrderCancellationConfirmation) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb6b8173ee11af27, []int{5}
}

func (m *OrderCancellationConfirmation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderCancellationConfirmation.Unmarshal(m, b)
}
func (m *OrderCancellationConfirmation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderCancellationConfirmation.Marshal(b, m, deterministic)
}
func (m *OrderCancellationConfirmation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderCancellationConfirmation.Merge(m, src)
}
func (m *OrderCancellationConfirmation) XXX_Size() int {
	return xxx_messageInfo_OrderCancellationConfirmation.Size(m)
}
func (m *OrderCancellationConfirmation) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderCancellationConfirmation.DiscardUnknown(m)
}

var xxx_messageInfo_OrderCancellationConfirmation proto.InternalMessageInfo

func (m *OrderCancellationConfirmation) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type OrderConfirmation struct {
	Order                 *Order   `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	Trades                []*Trade `protobuf:"bytes,2,rep,name=trades,proto3" json:"trades,omitempty"`
	PassiveOrdersAffected []*Order `protobuf:"bytes,3,rep,name=passiveOrdersAffected,proto3" json:"passiveOrdersAffected,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *OrderConfirmation) Reset()         { *m = OrderConfirmation{} }
func (m *OrderConfirmation) String() string { return proto.CompactTextString(m) }
func (*OrderConfirmation) ProtoMessage()    {}
func (*OrderConfirmation) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb6b8173ee11af27, []int{6}
}

func (m *OrderConfirmation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderConfirmation.Unmarshal(m, b)
}
func (m *OrderConfirmation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderConfirmation.Marshal(b, m, deterministic)
}
func (m *OrderConfirmation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderConfirmation.Merge(m, src)
}
func (m *OrderConfirmation) XXX_Size() int {
	return xxx_messageInfo_OrderConfirmation.Size(m)
}
func (m *OrderConfirmation) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderConfirmation.DiscardUnknown(m)
}

var xxx_messageInfo_OrderConfirmation proto.InternalMessageInfo

func (m *OrderConfirmation) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

func (m *OrderConfirmation) GetTrades() []*Trade {
	if m != nil {
		return m.Trades
	}
	return nil
}

func (m *OrderConfirmation) GetPassiveOrdersAffected() []*Order {
	if m != nil {
		return m.PassiveOrdersAffected
	}
	return nil
}

type Trade struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Market               string   `protobuf:"bytes,2,opt,name=market,proto3" json:"market,omitempty"`
	Price                uint64   `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Size                 uint64   `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Buyer                string   `protobuf:"bytes,5,opt,name=buyer,proto3" json:"buyer,omitempty"`
	Seller               string   `protobuf:"bytes,6,opt,name=seller,proto3" json:"seller,omitempty"`
	Aggressor            Side     `protobuf:"varint,7,opt,name=aggressor,proto3,enum=vega.Side" json:"aggressor,omitempty"`
	BuyOrder             string   `protobuf:"bytes,8,opt,name=buyOrder,proto3" json:"buyOrder,omitempty"`
	SellOrder            string   `protobuf:"bytes,9,opt,name=sellOrder,proto3" json:"sellOrder,omitempty"`
	Timestamp            int64    `protobuf:"varint,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Trade) Reset()         { *m = Trade{} }
func (m *Trade) String() string { return proto.CompactTextString(m) }
func (*Trade) ProtoMessage()    {}
func (*Trade) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb6b8173ee11af27, []int{7}
}

func (m *Trade) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Trade.Unmarshal(m, b)
}
func (m *Trade) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Trade.Marshal(b, m, deterministic)
}
func (m *Trade) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Trade.Merge(m, src)
}
func (m *Trade) XXX_Size() int {
	return xxx_messageInfo_Trade.Size(m)
}
func (m *Trade) XXX_DiscardUnknown() {
	xxx_messageInfo_Trade.DiscardUnknown(m)
}

var xxx_messageInfo_Trade proto.InternalMessageInfo

func (m *Trade) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Trade) GetMarket() string {
	if m != nil {
		return m.Market
	}
	return ""
}

func (m *Trade) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Trade) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Trade) GetBuyer() string {
	if m != nil {
		return m.Buyer
	}
	return ""
}

func (m *Trade) GetSeller() string {
	if m != nil {
		return m.Seller
	}
	return ""
}

func (m *Trade) GetAggressor() Side {
	if m != nil {
		return m.Aggressor
	}
	return Side_Buy
}

func (m *Trade) GetBuyOrder() string {
	if m != nil {
		return m.BuyOrder
	}
	return ""
}

func (m *Trade) GetSellOrder() string {
	if m != nil {
		return m.SellOrder
	}
	return ""
}

func (m *Trade) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type TradeSet struct {
	Trades               []*Trade `protobuf:"bytes,1,rep,name=trades,proto3" json:"trades,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TradeSet) Reset()         { *m = TradeSet{} }
func (m *TradeSet) String() string { return proto.CompactTextString(m) }
func (*TradeSet) ProtoMessage()    {}
func (*TradeSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb6b8173ee11af27, []int{8}
}

func (m *TradeSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TradeSet.Unmarshal(m, b)
}
func (m *TradeSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TradeSet.Marshal(b, m, deterministic)
}
func (m *TradeSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TradeSet.Merge(m, src)
}
func (m *TradeSet) XXX_Size() int {
	return xxx_messageInfo_TradeSet.Size(m)
}
func (m *TradeSet) XXX_DiscardUnknown() {
	xxx_messageInfo_TradeSet.DiscardUnknown(m)
}

var xxx_messageInfo_TradeSet proto.InternalMessageInfo

func (m *TradeSet) GetTrades() []*Trade {
	if m != nil {
		return m.Trades
	}
	return nil
}

type MarketData struct {
	BestBid              uint64   `protobuf:"varint,1,opt,name=bestBid,proto3" json:"bestBid,omitempty"`
	BestOffer            uint64   `protobuf:"varint,2,opt,name=bestOffer,proto3" json:"bestOffer,omitempty"`
	LastTradedPrice      uint64   `protobuf:"varint,3,opt,name=lastTradedPrice,proto3" json:"lastTradedPrice,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MarketData) Reset()         { *m = MarketData{} }
func (m *MarketData) String() string { return proto.CompactTextString(m) }
func (*MarketData) ProtoMessage()    {}
func (*MarketData) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb6b8173ee11af27, []int{9}
}

func (m *MarketData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarketData.Unmarshal(m, b)
}
func (m *MarketData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarketData.Marshal(b, m, deterministic)
}
func (m *MarketData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarketData.Merge(m, src)
}
func (m *MarketData) XXX_Size() int {
	return xxx_messageInfo_MarketData.Size(m)
}
func (m *MarketData) XXX_DiscardUnknown() {
	xxx_messageInfo_MarketData.DiscardUnknown(m)
}

var xxx_messageInfo_MarketData proto.InternalMessageInfo

func (m *MarketData) GetBestBid() uint64 {
	if m != nil {
		return m.BestBid
	}
	return 0
}

func (m *MarketData) GetBestOffer() uint64 {
	if m != nil {
		return m.BestOffer
	}
	return 0
}

func (m *MarketData) GetLastTradedPrice() uint64 {
	if m != nil {
		return m.LastTradedPrice
	}
	return 0
}

type Candle struct {
	Timestamp            int64    `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Datetime             string   `protobuf:"bytes,2,opt,name=datetime,proto3" json:"datetime,omitempty"`
	High                 uint64   `protobuf:"varint,3,opt,name=high,proto3" json:"high,omitempty"`
	Low                  uint64   `protobuf:"varint,4,opt,name=low,proto3" json:"low,omitempty"`
	Open                 uint64   `protobuf:"varint,5,opt,name=open,proto3" json:"open,omitempty"`
	Close                uint64   `protobuf:"varint,6,opt,name=close,proto3" json:"close,omitempty"`
	Volume               uint64   `protobuf:"varint,7,opt,name=volume,proto3" json:"volume,omitempty"`
	Interval             Interval `protobuf:"varint,8,opt,name=interval,proto3,enum=vega.Interval" json:"interval,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Candle) Reset()         { *m = Candle{} }
func (m *Candle) String() string { return proto.CompactTextString(m) }
func (*Candle) ProtoMessage()    {}
func (*Candle) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb6b8173ee11af27, []int{10}
}

func (m *Candle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Candle.Unmarshal(m, b)
}
func (m *Candle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Candle.Marshal(b, m, deterministic)
}
func (m *Candle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Candle.Merge(m, src)
}
func (m *Candle) XXX_Size() int {
	return xxx_messageInfo_Candle.Size(m)
}
func (m *Candle) XXX_DiscardUnknown() {
	xxx_messageInfo_Candle.DiscardUnknown(m)
}

var xxx_messageInfo_Candle proto.InternalMessageInfo

func (m *Candle) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Candle) GetDatetime() string {
	if m != nil {
		return m.Datetime
	}
	return ""
}

func (m *Candle) GetHigh() uint64 {
	if m != nil {
		return m.High
	}
	return 0
}

func (m *Candle) GetLow() uint64 {
	if m != nil {
		return m.Low
	}
	return 0
}

func (m *Candle) GetOpen() uint64 {
	if m != nil {
		return m.Open
	}
	return 0
}

func (m *Candle) GetClose() uint64 {
	if m != nil {
		return m.Close
	}
	return 0
}

func (m *Candle) GetVolume() uint64 {
	if m != nil {
		return m.Volume
	}
	return 0
}

func (m *Candle) GetInterval() Interval {
	if m != nil {
		return m.Interval
	}
	return Interval_I1M
}

type PriceLevel struct {
	Price                uint64   `protobuf:"varint,1,opt,name=price,proto3" json:"price,omitempty"`
	NumberOfOrders       uint64   `protobuf:"varint,2,opt,name=numberOfOrders,proto3" json:"numberOfOrders,omitempty"`
	Volume               uint64   `protobuf:"varint,3,opt,name=volume,proto3" json:"volume,omitempty"`
	CumulativeVolume     uint64   `protobuf:"varint,4,opt,name=cumulativeVolume,proto3" json:"cumulativeVolume,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PriceLevel) Reset()         { *m = PriceLevel{} }
func (m *PriceLevel) String() string { return proto.CompactTextString(m) }
func (*PriceLevel) ProtoMessage()    {}
func (*PriceLevel) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb6b8173ee11af27, []int{11}
}

func (m *PriceLevel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PriceLevel.Unmarshal(m, b)
}
func (m *PriceLevel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PriceLevel.Marshal(b, m, deterministic)
}
func (m *PriceLevel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PriceLevel.Merge(m, src)
}
func (m *PriceLevel) XXX_Size() int {
	return xxx_messageInfo_PriceLevel.Size(m)
}
func (m *PriceLevel) XXX_DiscardUnknown() {
	xxx_messageInfo_PriceLevel.DiscardUnknown(m)
}

var xxx_messageInfo_PriceLevel proto.InternalMessageInfo

func (m *PriceLevel) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *PriceLevel) GetNumberOfOrders() uint64 {
	if m != nil {
		return m.NumberOfOrders
	}
	return 0
}

func (m *PriceLevel) GetVolume() uint64 {
	if m != nil {
		return m.Volume
	}
	return 0
}

func (m *PriceLevel) GetCumulativeVolume() uint64 {
	if m != nil {
		return m.CumulativeVolume
	}
	return 0
}

type MarketDepth struct {
	Name                 string        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Buy                  []*PriceLevel `protobuf:"bytes,2,rep,name=buy,proto3" json:"buy,omitempty"`
	Sell                 []*PriceLevel `protobuf:"bytes,3,rep,name=sell,proto3" json:"sell,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *MarketDepth) Reset()         { *m = MarketDepth{} }
func (m *MarketDepth) String() string { return proto.CompactTextString(m) }
func (*MarketDepth) ProtoMessage()    {}
func (*MarketDepth) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb6b8173ee11af27, []int{12}
}

func (m *MarketDepth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarketDepth.Unmarshal(m, b)
}
func (m *MarketDepth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarketDepth.Marshal(b, m, deterministic)
}
func (m *MarketDepth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarketDepth.Merge(m, src)
}
func (m *MarketDepth) XXX_Size() int {
	return xxx_messageInfo_MarketDepth.Size(m)
}
func (m *MarketDepth) XXX_DiscardUnknown() {
	xxx_messageInfo_MarketDepth.DiscardUnknown(m)
}

var xxx_messageInfo_MarketDepth proto.InternalMessageInfo

func (m *MarketDepth) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MarketDepth) GetBuy() []*PriceLevel {
	if m != nil {
		return m.Buy
	}
	return nil
}

func (m *MarketDepth) GetSell() []*PriceLevel {
	if m != nil {
		return m.Sell
	}
	return nil
}

type MarketPosition struct {
	Market               string   `protobuf:"bytes,1,opt,name=market,proto3" json:"market,omitempty"`
	RealisedVolume       int64    `protobuf:"varint,2,opt,name=realisedVolume,proto3" json:"realisedVolume,omitempty"`
	RealisedPNL          int64    `protobuf:"varint,3,opt,name=realisedPNL,proto3" json:"realisedPNL,omitempty"`
	UnrealisedVolume     int64    `protobuf:"varint,4,opt,name=unrealisedVolume,proto3" json:"unrealisedVolume,omitempty"`
	UnrealisedPNL        int64    `protobuf:"varint,5,opt,name=unrealisedPNL,proto3" json:"unrealisedPNL,omitempty"`
	AverageEntryPrice    uint64   `protobuf:"varint,6,opt,name=averageEntryPrice,proto3" json:"averageEntryPrice,omitempty"`
	MinimumMargin        int64    `protobuf:"varint,7,opt,name=minimumMargin,proto3" json:"minimumMargin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MarketPosition) Reset()         { *m = MarketPosition{} }
func (m *MarketPosition) String() string { return proto.CompactTextString(m) }
func (*MarketPosition) ProtoMessage()    {}
func (*MarketPosition) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb6b8173ee11af27, []int{13}
}

func (m *MarketPosition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarketPosition.Unmarshal(m, b)
}
func (m *MarketPosition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarketPosition.Marshal(b, m, deterministic)
}
func (m *MarketPosition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarketPosition.Merge(m, src)
}
func (m *MarketPosition) XXX_Size() int {
	return xxx_messageInfo_MarketPosition.Size(m)
}
func (m *MarketPosition) XXX_DiscardUnknown() {
	xxx_messageInfo_MarketPosition.DiscardUnknown(m)
}

var xxx_messageInfo_MarketPosition proto.InternalMessageInfo

func (m *MarketPosition) GetMarket() string {
	if m != nil {
		return m.Market
	}
	return ""
}

func (m *MarketPosition) GetRealisedVolume() int64 {
	if m != nil {
		return m.RealisedVolume
	}
	return 0
}

func (m *MarketPosition) GetRealisedPNL() int64 {
	if m != nil {
		return m.RealisedPNL
	}
	return 0
}

func (m *MarketPosition) GetUnrealisedVolume() int64 {
	if m != nil {
		return m.UnrealisedVolume
	}
	return 0
}

func (m *MarketPosition) GetUnrealisedPNL() int64 {
	if m != nil {
		return m.UnrealisedPNL
	}
	return 0
}

func (m *MarketPosition) GetAverageEntryPrice() uint64 {
	if m != nil {
		return m.AverageEntryPrice
	}
	return 0
}

func (m *MarketPosition) GetMinimumMargin() int64 {
	if m != nil {
		return m.MinimumMargin
	}
	return 0
}

type Statistics struct {
	BlockHeight           uint64      `protobuf:"varint,1,opt,name=blockHeight,proto3" json:"blockHeight,omitempty"`
	BacklogLength         uint64      `protobuf:"varint,2,opt,name=backlogLength,proto3" json:"backlogLength,omitempty"`
	TotalPeers            uint64      `protobuf:"varint,3,opt,name=totalPeers,proto3" json:"totalPeers,omitempty"`
	GenesisTime           string      `protobuf:"bytes,4,opt,name=genesisTime,proto3" json:"genesisTime,omitempty"`
	CurrentTime           string      `protobuf:"bytes,5,opt,name=currentTime,proto3" json:"currentTime,omitempty"`
	VegaTime              string      `protobuf:"bytes,6,opt,name=vegaTime,proto3" json:"vegaTime,omitempty"`
	Status                ChainStatus `protobuf:"varint,7,opt,name=status,proto3,enum=vega.ChainStatus" json:"status,omitempty"`
	TxPerBlock            uint64      `protobuf:"varint,8,opt,name=txPerBlock,proto3" json:"txPerBlock,omitempty"`
	AverageTxBytes        uint64      `protobuf:"varint,9,opt,name=averageTxBytes,proto3" json:"averageTxBytes,omitempty"`
	AverageOrdersPerBlock uint64      `protobuf:"varint,10,opt,name=averageOrdersPerBlock,proto3" json:"averageOrdersPerBlock,omitempty"`
	TradesPerSecond       uint64      `protobuf:"varint,11,opt,name=tradesPerSecond,proto3" json:"tradesPerSecond,omitempty"`
	OrdersPerSecond       uint64      `protobuf:"varint,12,opt,name=ordersPerSecond,proto3" json:"ordersPerSecond,omitempty"`
	TotalMarkets          uint64      `protobuf:"varint,13,opt,name=totalMarkets,proto3" json:"totalMarkets,omitempty"`
	TotalParties          uint64      `protobuf:"varint,14,opt,name=totalParties,proto3" json:"totalParties,omitempty"`
	AppVersionHash        string      `protobuf:"bytes,15,opt,name=appVersionHash,proto3" json:"appVersionHash,omitempty"`
	AppVersion            string      `protobuf:"bytes,16,opt,name=appVersion,proto3" json:"appVersion,omitempty"`
	Parties               []string    `protobuf:"bytes,17,rep,name=Parties,proto3" json:"Parties,omitempty"`
	TotalAmendOrder       uint64      `protobuf:"varint,18,opt,name=totalAmendOrder,proto3" json:"totalAmendOrder,omitempty"`
	TotalCancelOrder      uint64      `protobuf:"varint,19,opt,name=totalCancelOrder,proto3" json:"totalCancelOrder,omitempty"`
	TotalCreateOrder      uint64      `protobuf:"varint,20,opt,name=totalCreateOrder,proto3" json:"totalCreateOrder,omitempty"`
	TotalOrders           uint64      `protobuf:"varint,21,opt,name=totalOrders,proto3" json:"totalOrders,omitempty"`
	TotalTrades           uint64      `protobuf:"varint,22,opt,name=totalTrades,proto3" json:"totalTrades,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}    `json:"-"`
	XXX_unrecognized      []byte      `json:"-"`
	XXX_sizecache         int32       `json:"-"`
}

func (m *Statistics) Reset()         { *m = Statistics{} }
func (m *Statistics) String() string { return proto.CompactTextString(m) }
func (*Statistics) ProtoMessage()    {}
func (*Statistics) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb6b8173ee11af27, []int{14}
}

func (m *Statistics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Statistics.Unmarshal(m, b)
}
func (m *Statistics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Statistics.Marshal(b, m, deterministic)
}
func (m *Statistics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Statistics.Merge(m, src)
}
func (m *Statistics) XXX_Size() int {
	return xxx_messageInfo_Statistics.Size(m)
}
func (m *Statistics) XXX_DiscardUnknown() {
	xxx_messageInfo_Statistics.DiscardUnknown(m)
}

var xxx_messageInfo_Statistics proto.InternalMessageInfo

func (m *Statistics) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *Statistics) GetBacklogLength() uint64 {
	if m != nil {
		return m.BacklogLength
	}
	return 0
}

func (m *Statistics) GetTotalPeers() uint64 {
	if m != nil {
		return m.TotalPeers
	}
	return 0
}

func (m *Statistics) GetGenesisTime() string {
	if m != nil {
		return m.GenesisTime
	}
	return ""
}

func (m *Statistics) GetCurrentTime() string {
	if m != nil {
		return m.CurrentTime
	}
	return ""
}

func (m *Statistics) GetVegaTime() string {
	if m != nil {
		return m.VegaTime
	}
	return ""
}

func (m *Statistics) GetStatus() ChainStatus {
	if m != nil {
		return m.Status
	}
	return ChainStatus_DISCONNECTED
}

func (m *Statistics) GetTxPerBlock() uint64 {
	if m != nil {
		return m.TxPerBlock
	}
	return 0
}

func (m *Statistics) GetAverageTxBytes() uint64 {
	if m != nil {
		return m.AverageTxBytes
	}
	return 0
}

func (m *Statistics) GetAverageOrdersPerBlock() uint64 {
	if m != nil {
		return m.AverageOrdersPerBlock
	}
	return 0
}

func (m *Statistics) GetTradesPerSecond() uint64 {
	if m != nil {
		return m.TradesPerSecond
	}
	return 0
}

func (m *Statistics) GetOrdersPerSecond() uint64 {
	if m != nil {
		return m.OrdersPerSecond
	}
	return 0
}

func (m *Statistics) GetTotalMarkets() uint64 {
	if m != nil {
		return m.TotalMarkets
	}
	return 0
}

func (m *Statistics) GetTotalParties() uint64 {
	if m != nil {
		return m.TotalParties
	}
	return 0
}

func (m *Statistics) GetAppVersionHash() string {
	if m != nil {
		return m.AppVersionHash
	}
	return ""
}

func (m *Statistics) GetAppVersion() string {
	if m != nil {
		return m.AppVersion
	}
	return ""
}

func (m *Statistics) GetParties() []string {
	if m != nil {
		return m.Parties
	}
	return nil
}

func (m *Statistics) GetTotalAmendOrder() uint64 {
	if m != nil {
		return m.TotalAmendOrder
	}
	return 0
}

func (m *Statistics) GetTotalCancelOrder() uint64 {
	if m != nil {
		return m.TotalCancelOrder
	}
	return 0
}

func (m *Statistics) GetTotalCreateOrder() uint64 {
	if m != nil {
		return m.TotalCreateOrder
	}
	return 0
}

func (m *Statistics) GetTotalOrders() uint64 {
	if m != nil {
		return m.TotalOrders
	}
	return 0
}

func (m *Statistics) GetTotalTrades() uint64 {
	if m != nil {
		return m.TotalTrades
	}
	return 0
}

type PendingOrder struct {
	Reference            string       `protobuf:"bytes,1,opt,name=reference,proto3" json:"reference,omitempty"`
	Price                uint64       `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	Type                 Order_Type   `protobuf:"varint,3,opt,name=type,proto3,enum=vega.Order_Type" json:"type,omitempty"`
	Side                 Side         `protobuf:"varint,4,opt,name=side,proto3,enum=vega.Side" json:"side,omitempty"`
	MarketID             string       `protobuf:"bytes,5,opt,name=marketID,proto3" json:"marketID,omitempty"`
	Size                 uint64       `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
	Party                string       `protobuf:"bytes,7,opt,name=party,proto3" json:"party,omitempty"`
	Status               Order_Status `protobuf:"varint,8,opt,name=status,proto3,enum=vega.Order_Status" json:"status,omitempty"`
	Id                   string       `protobuf:"bytes,9,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PendingOrder) Reset()         { *m = PendingOrder{} }
func (m *PendingOrder) String() string { return proto.CompactTextString(m) }
func (*PendingOrder) ProtoMessage()    {}
func (*PendingOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb6b8173ee11af27, []int{15}
}

func (m *PendingOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PendingOrder.Unmarshal(m, b)
}
func (m *PendingOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PendingOrder.Marshal(b, m, deterministic)
}
func (m *PendingOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PendingOrder.Merge(m, src)
}
func (m *PendingOrder) XXX_Size() int {
	return xxx_messageInfo_PendingOrder.Size(m)
}
func (m *PendingOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_PendingOrder.DiscardUnknown(m)
}

var xxx_messageInfo_PendingOrder proto.InternalMessageInfo

func (m *PendingOrder) GetReference() string {
	if m != nil {
		return m.Reference
	}
	return ""
}

func (m *PendingOrder) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *PendingOrder) GetType() Order_Type {
	if m != nil {
		return m.Type
	}
	return Order_GTC
}

func (m *PendingOrder) GetSide() Side {
	if m != nil {
		return m.Side
	}
	return Side_Buy
}

func (m *PendingOrder) GetMarketID() string {
	if m != nil {
		return m.MarketID
	}
	return ""
}

func (m *PendingOrder) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *PendingOrder) GetParty() string {
	if m != nil {
		return m.Party
	}
	return ""
}

func (m *PendingOrder) GetStatus() Order_Status {
	if m != nil {
		return m.Status
	}
	return Order_Active
}

func (m *PendingOrder) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type OrderAmendment struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Party                string   `protobuf:"bytes,2,opt,name=party,proto3" json:"party,omitempty"`
	Price                uint64   `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Size                 uint64   `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	ExpiresAt            int64    `protobuf:"varint,5,opt,name=expiresAt,proto3" json:"expiresAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderAmendment) Reset()         { *m = OrderAmendment{} }
func (m *OrderAmendment) String() string { return proto.CompactTextString(m) }
func (*OrderAmendment) ProtoMessage()    {}
func (*OrderAmendment) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb6b8173ee11af27, []int{16}
}

func (m *OrderAmendment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderAmendment.Unmarshal(m, b)
}
func (m *OrderAmendment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderAmendment.Marshal(b, m, deterministic)
}
func (m *OrderAmendment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderAmendment.Merge(m, src)
}
func (m *OrderAmendment) XXX_Size() int {
	return xxx_messageInfo_OrderAmendment.Size(m)
}
func (m *OrderAmendment) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderAmendment.DiscardUnknown(m)
}

var xxx_messageInfo_OrderAmendment proto.InternalMessageInfo

func (m *OrderAmendment) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *OrderAmendment) GetParty() string {
	if m != nil {
		return m.Party
	}
	return ""
}

func (m *OrderAmendment) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *OrderAmendment) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *OrderAmendment) GetExpiresAt() int64 {
	if m != nil {
		return m.ExpiresAt
	}
	return 0
}

type OrderSubmission struct {
	Id                   string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MarketId             string     `protobuf:"bytes,2,opt,name=marketId,proto3" json:"marketId,omitempty"`
	Party                string     `protobuf:"bytes,3,opt,name=party,proto3" json:"party,omitempty"`
	Price                uint64     `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Size                 uint64     `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	Side                 Side       `protobuf:"varint,6,opt,name=side,proto3,enum=vega.Side" json:"side,omitempty"`
	Type                 Order_Type `protobuf:"varint,7,opt,name=type,proto3,enum=vega.Order_Type" json:"type,omitempty"`
	ExpiresAt            int64      `protobuf:"varint,8,opt,name=expiresAt,proto3" json:"expiresAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *OrderSubmission) Reset()         { *m = OrderSubmission{} }
func (m *OrderSubmission) String() string { return proto.CompactTextString(m) }
func (*OrderSubmission) ProtoMessage()    {}
func (*OrderSubmission) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb6b8173ee11af27, []int{17}
}

func (m *OrderSubmission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderSubmission.Unmarshal(m, b)
}
func (m *OrderSubmission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderSubmission.Marshal(b, m, deterministic)
}
func (m *OrderSubmission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderSubmission.Merge(m, src)
}
func (m *OrderSubmission) XXX_Size() int {
	return xxx_messageInfo_OrderSubmission.Size(m)
}
func (m *OrderSubmission) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderSubmission.DiscardUnknown(m)
}

var xxx_messageInfo_OrderSubmission proto.InternalMessageInfo

func (m *OrderSubmission) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *OrderSubmission) GetMarketId() string {
	if m != nil {
		return m.MarketId
	}
	return ""
}

func (m *OrderSubmission) GetParty() string {
	if m != nil {
		return m.Party
	}
	return ""
}

func (m *OrderSubmission) GetPrice() uint64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *OrderSubmission) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *OrderSubmission) GetSide() Side {
	if m != nil {
		return m.Side
	}
	return Side_Buy
}

func (m *OrderSubmission) GetType() Order_Type {
	if m != nil {
		return m.Type
	}
	return Order_GTC
}

func (m *OrderSubmission) GetExpiresAt() int64 {
	if m != nil {
		return m.ExpiresAt
	}
	return 0
}

type OrderCancellation struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MarketId             string   `protobuf:"bytes,2,opt,name=marketId,proto3" json:"marketId,omitempty"`
	Party                string   `protobuf:"bytes,3,opt,name=party,proto3" json:"party,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderCancellation) Reset()         { *m = OrderCancellation{} }
func (m *OrderCancellation) String() string { return proto.CompactTextString(m) }
func (*OrderCancellation) ProtoMessage()    {}
func (*OrderCancellation) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb6b8173ee11af27, []int{18}
}

func (m *OrderCancellation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderCancellation.Unmarshal(m, b)
}
func (m *OrderCancellation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderCancellation.Marshal(b, m, deterministic)
}
func (m *OrderCancellation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderCancellation.Merge(m, src)
}
func (m *OrderCancellation) XXX_Size() int {
	return xxx_messageInfo_OrderCancellation.Size(m)
}
func (m *OrderCancellation) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderCancellation.DiscardUnknown(m)
}

var xxx_messageInfo_OrderCancellation proto.InternalMessageInfo

func (m *OrderCancellation) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *OrderCancellation) GetMarketId() string {
	if m != nil {
		return m.MarketId
	}
	return ""
}

func (m *OrderCancellation) GetParty() string {
	if m != nil {
		return m.Party
	}
	return ""
}

type Account struct {
	Id                   string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Owner                string      `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Balance              int64       `protobuf:"varint,3,opt,name=balance,proto3" json:"balance,omitempty"`
	Asset                string      `protobuf:"bytes,4,opt,name=asset,proto3" json:"asset,omitempty"`
	Market               string      `protobuf:"bytes,5,opt,name=market,proto3" json:"market,omitempty"`
	Type                 AccountType `protobuf:"varint,6,opt,name=type,proto3,enum=vega.AccountType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb6b8173ee11af27, []int{19}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Account) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Account) GetBalance() int64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *Account) GetAsset() string {
	if m != nil {
		return m.Asset
	}
	return ""
}

func (m *Account) GetMarket() string {
	if m != nil {
		return m.Market
	}
	return ""
}

func (m *Account) GetType() AccountType {
	if m != nil {
		return m.Type
	}
	return AccountType_INSURANCE
}

type FinancialAmount struct {
	Amount               int64    `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Asset                string   `protobuf:"bytes,2,opt,name=asset,proto3" json:"asset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FinancialAmount) Reset()         { *m = FinancialAmount{} }
func (m *FinancialAmount) String() string { return proto.CompactTextString(m) }
func (*FinancialAmount) ProtoMessage()    {}
func (*FinancialAmount) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb6b8173ee11af27, []int{20}
}

func (m *FinancialAmount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FinancialAmount.Unmarshal(m, b)
}
func (m *FinancialAmount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FinancialAmount.Marshal(b, m, deterministic)
}
func (m *FinancialAmount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinancialAmount.Merge(m, src)
}
func (m *FinancialAmount) XXX_Size() int {
	return xxx_messageInfo_FinancialAmount.Size(m)
}
func (m *FinancialAmount) XXX_DiscardUnknown() {
	xxx_messageInfo_FinancialAmount.DiscardUnknown(m)
}

var xxx_messageInfo_FinancialAmount proto.InternalMessageInfo

func (m *FinancialAmount) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *FinancialAmount) GetAsset() string {
	if m != nil {
		return m.Asset
	}
	return ""
}

type SettlePosition struct {
	Owner                string           `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Size                 uint64           `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Amount               *FinancialAmount `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Type                 SettleType       `protobuf:"varint,4,opt,name=type,proto3,enum=vega.SettleType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SettlePosition) Reset()         { *m = SettlePosition{} }
func (m *SettlePosition) String() string { return proto.CompactTextString(m) }
func (*SettlePosition) ProtoMessage()    {}
func (*SettlePosition) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb6b8173ee11af27, []int{21}
}

func (m *SettlePosition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SettlePosition.Unmarshal(m, b)
}
func (m *SettlePosition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SettlePosition.Marshal(b, m, deterministic)
}
func (m *SettlePosition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SettlePosition.Merge(m, src)
}
func (m *SettlePosition) XXX_Size() int {
	return xxx_messageInfo_SettlePosition.Size(m)
}
func (m *SettlePosition) XXX_DiscardUnknown() {
	xxx_messageInfo_SettlePosition.DiscardUnknown(m)
}

var xxx_messageInfo_SettlePosition proto.InternalMessageInfo

func (m *SettlePosition) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *SettlePosition) GetSize() uint64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *SettlePosition) GetAmount() *FinancialAmount {
	if m != nil {
		return m.Amount
	}
	return nil
}

func (m *SettlePosition) GetType() SettleType {
	if m != nil {
		return m.Type
	}
	return SettleType_LOSS
}

type TransferRequest struct {
	FromAccount          []*Account `protobuf:"bytes,1,rep,name=fromAccount,proto3" json:"fromAccount,omitempty"`
	ToAccount            []*Account `protobuf:"bytes,2,rep,name=toAccount,proto3" json:"toAccount,omitempty"`
	Amount               uint64     `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	MinAmount            uint64     `protobuf:"varint,4,opt,name=minAmount,proto3" json:"minAmount,omitempty"`
	Asset                string     `protobuf:"bytes,5,opt,name=asset,proto3" json:"asset,omitempty"`
	Reference            string     `protobuf:"bytes,6,opt,name=reference,proto3" json:"reference,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *TransferRequest) Reset()         { *m = TransferRequest{} }
func (m *TransferRequest) String() string { return proto.CompactTextString(m) }
func (*TransferRequest) ProtoMessage()    {}
func (*TransferRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb6b8173ee11af27, []int{22}
}

func (m *TransferRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferRequest.Unmarshal(m, b)
}
func (m *TransferRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferRequest.Marshal(b, m, deterministic)
}
func (m *TransferRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferRequest.Merge(m, src)
}
func (m *TransferRequest) XXX_Size() int {
	return xxx_messageInfo_TransferRequest.Size(m)
}
func (m *TransferRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TransferRequest proto.InternalMessageInfo

func (m *TransferRequest) GetFromAccount() []*Account {
	if m != nil {
		return m.FromAccount
	}
	return nil
}

func (m *TransferRequest) GetToAccount() []*Account {
	if m != nil {
		return m.ToAccount
	}
	return nil
}

func (m *TransferRequest) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *TransferRequest) GetMinAmount() uint64 {
	if m != nil {
		return m.MinAmount
	}
	return 0
}

func (m *TransferRequest) GetAsset() string {
	if m != nil {
		return m.Asset
	}
	return ""
}

func (m *TransferRequest) GetReference() string {
	if m != nil {
		return m.Reference
	}
	return ""
}

type LedgerEntry struct {
	FromAccount          string   `protobuf:"bytes,1,opt,name=fromAccount,proto3" json:"fromAccount,omitempty"`
	ToAccount            string   `protobuf:"bytes,2,opt,name=toAccount,proto3" json:"toAccount,omitempty"`
	Amount               int64    `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Reference            string   `protobuf:"bytes,4,opt,name=reference,proto3" json:"reference,omitempty"`
	Type                 string   `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Timestamp            int64    `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LedgerEntry) Reset()         { *m = LedgerEntry{} }
func (m *LedgerEntry) String() string { return proto.CompactTextString(m) }
func (*LedgerEntry) ProtoMessage()    {}
func (*LedgerEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb6b8173ee11af27, []int{23}
}

func (m *LedgerEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LedgerEntry.Unmarshal(m, b)
}
func (m *LedgerEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LedgerEntry.Marshal(b, m, deterministic)
}
func (m *LedgerEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LedgerEntry.Merge(m, src)
}
func (m *LedgerEntry) XXX_Size() int {
	return xxx_messageInfo_LedgerEntry.Size(m)
}
func (m *LedgerEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_LedgerEntry.DiscardUnknown(m)
}

var xxx_messageInfo_LedgerEntry proto.InternalMessageInfo

func (m *LedgerEntry) GetFromAccount() string {
	if m != nil {
		return m.FromAccount
	}
	return ""
}

func (m *LedgerEntry) GetToAccount() string {
	if m != nil {
		return m.ToAccount
	}
	return ""
}

func (m *LedgerEntry) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *LedgerEntry) GetReference() string {
	if m != nil {
		return m.Reference
	}
	return ""
}

func (m *LedgerEntry) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *LedgerEntry) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type TransferBalance struct {
	Account              *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Balance              int64    `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransferBalance) Reset()         { *m = TransferBalance{} }
func (m *TransferBalance) String() string { return proto.CompactTextString(m) }
func (*TransferBalance) ProtoMessage()    {}
func (*TransferBalance) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb6b8173ee11af27, []int{24}
}

func (m *TransferBalance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferBalance.Unmarshal(m, b)
}
func (m *TransferBalance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferBalance.Marshal(b, m, deterministic)
}
func (m *TransferBalance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferBalance.Merge(m, src)
}
func (m *TransferBalance) XXX_Size() int {
	return xxx_messageInfo_TransferBalance.Size(m)
}
func (m *TransferBalance) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferBalance.DiscardUnknown(m)
}

var xxx_messageInfo_TransferBalance proto.InternalMessageInfo

func (m *TransferBalance) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *TransferBalance) GetBalance() int64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

type TransferResponse struct {
	Transfers            []*LedgerEntry     `protobuf:"bytes,1,rep,name=transfers,proto3" json:"transfers,omitempty"`
	Balances             []*TransferBalance `protobuf:"bytes,2,rep,name=balances,proto3" json:"balances,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *TransferResponse) Reset()         { *m = TransferResponse{} }
func (m *TransferResponse) String() string { return proto.CompactTextString(m) }
func (*TransferResponse) ProtoMessage()    {}
func (*TransferResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb6b8173ee11af27, []int{25}
}

func (m *TransferResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransferResponse.Unmarshal(m, b)
}
func (m *TransferResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransferResponse.Marshal(b, m, deterministic)
}
func (m *TransferResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransferResponse.Merge(m, src)
}
func (m *TransferResponse) XXX_Size() int {
	return xxx_messageInfo_TransferResponse.Size(m)
}
func (m *TransferResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TransferResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TransferResponse proto.InternalMessageInfo

func (m *TransferResponse) GetTransfers() []*LedgerEntry {
	if m != nil {
		return m.Transfers
	}
	return nil
}

func (m *TransferResponse) GetBalances() []*TransferBalance {
	if m != nil {
		return m.Balances
	}
	return nil
}

func init() {
	proto.RegisterEnum("vega.Side", Side_name, Side_value)
	proto.RegisterEnum("vega.Interval", Interval_name, Interval_value)
	proto.RegisterEnum("vega.OrderError", OrderError_name, OrderError_value)
	proto.RegisterEnum("vega.ChainStatus", ChainStatus_name, ChainStatus_value)
	proto.RegisterEnum("vega.AccountType", AccountType_name, AccountType_value)
	proto.RegisterEnum("vega.SettleType", SettleType_name, SettleType_value)
	proto.RegisterEnum("vega.Order_Type", Order_Type_name, Order_Type_value)
	proto.RegisterEnum("vega.Order_Status", Order_Status_name, Order_Status_value)
	proto.RegisterType((*Amount)(nil), "vega.Amount")
	proto.RegisterType((*Party)(nil), "vega.Party")
	proto.RegisterType((*RiskFactor)(nil), "vega.RiskFactor")
	proto.RegisterType((*RiskResult)(nil), "vega.RiskResult")
	proto.RegisterMapType((map[string]*RiskFactor)(nil), "vega.RiskResult.PredictedNextRiskFactorsEntry")
	proto.RegisterMapType((map[string]*RiskFactor)(nil), "vega.RiskResult.RiskFactorsEntry")
	proto.RegisterType((*Order)(nil), "vega.Order")
	proto.RegisterType((*OrderCancellationConfirmation)(nil), "vega.OrderCancellationConfirmation")
	proto.RegisterType((*OrderConfirmation)(nil), "vega.OrderConfirmation")
	proto.RegisterType((*Trade)(nil), "vega.Trade")
	proto.RegisterType((*TradeSet)(nil), "vega.TradeSet")
	proto.RegisterType((*MarketData)(nil), "vega.MarketData")
	proto.RegisterType((*Candle)(nil), "vega.Candle")
	proto.RegisterType((*PriceLevel)(nil), "vega.PriceLevel")
	proto.RegisterType((*MarketDepth)(nil), "vega.MarketDepth")
	proto.RegisterType((*MarketPosition)(nil), "vega.MarketPosition")
	proto.RegisterType((*Statistics)(nil), "vega.Statistics")
	proto.RegisterType((*PendingOrder)(nil), "vega.PendingOrder")
	proto.RegisterType((*OrderAmendment)(nil), "vega.OrderAmendment")
	proto.RegisterType((*OrderSubmission)(nil), "vega.OrderSubmission")
	proto.RegisterType((*OrderCancellation)(nil), "vega.OrderCancellation")
	proto.RegisterType((*Account)(nil), "vega.Account")
	proto.RegisterType((*FinancialAmount)(nil), "vega.FinancialAmount")
	proto.RegisterType((*SettlePosition)(nil), "vega.SettlePosition")
	proto.RegisterType((*TransferRequest)(nil), "vega.TransferRequest")
	proto.RegisterType((*LedgerEntry)(nil), "vega.LedgerEntry")
	proto.RegisterType((*TransferBalance)(nil), "vega.TransferBalance")
	proto.RegisterType((*TransferResponse)(nil), "vega.TransferResponse")
}

func init() { proto.RegisterFile("proto/vega.proto", fileDescriptor_bb6b8173ee11af27) }

var fileDescriptor_bb6b8173ee11af27 = []byte{
	// 2316 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x58, 0xdf, 0x6e, 0xdb, 0xc8,
	0xd5, 0x37, 0x29, 0x4a, 0xb6, 0x8e, 0x12, 0x9b, 0x99, 0xd8, 0x59, 0xad, 0x37, 0x9b, 0x38, 0xfc,
	0xf6, 0x4b, 0x5d, 0xb7, 0xb1, 0x9b, 0xb4, 0xbb, 0x28, 0x0a, 0x14, 0x05, 0x6d, 0xd1, 0x09, 0x11,
	0x89, 0xd2, 0x8e, 0xe4, 0xa4, 0x5d, 0xa0, 0x30, 0x68, 0x71, 0x2c, 0xb3, 0xa6, 0x48, 0x95, 0x1c,
	0x29, 0x71, 0xdf, 0xa0, 0xbd, 0x68, 0xef, 0x8a, 0x5e, 0xf5, 0xbe, 0x0f, 0xd0, 0x07, 0xe8, 0x7d,
	0x2f, 0x7a, 0x55, 0xa0, 0x57, 0x45, 0xfb, 0x24, 0xc5, 0xfc, 0x21, 0x39, 0xa2, 0xed, 0x0d, 0x16,
	0x7b, 0xa5, 0x99, 0xdf, 0x39, 0x73, 0xe6, 0x9c, 0x33, 0xbf, 0x39, 0x73, 0x28, 0x30, 0x67, 0x69,
	0x42, 0x93, 0x83, 0x05, 0x99, 0xf8, 0xfb, 0x7c, 0x88, 0x0c, 0x36, 0xde, 0xfe, 0x62, 0x12, 0xd2,
	0x8b, 0xf9, 0xd9, 0xfe, 0x38, 0x99, 0x1e, 0x4c, 0xdf, 0x85, 0xf4, 0x32, 0x79, 0x77, 0x30, 0x49,
	0x9e, 0x71, 0x95, 0x67, 0x0b, 0x3f, 0x0a, 0x03, 0x9f, 0x26, 0x69, 0x76, 0x50, 0x0c, 0xc5, 0x6a,
	0xeb, 0x11, 0x34, 0xec, 0x69, 0x32, 0x8f, 0x29, 0xda, 0x84, 0xfa, 0xc2, 0x8f, 0xe6, 0xa4, 0xad,
	0xed, 0x68, 0xbb, 0x4d, 0x2c, 0x26, 0xd6, 0x5b, 0xa8, 0x0f, 0xfc, 0x94, 0x5e, 0xa1, 0x6d, 0x30,
	0x62, 0x7f, 0x2a, 0xa5, 0x87, 0x8d, 0xff, 0xfe, 0xfb, 0xb1, 0xbe, 0xa3, 0x61, 0x8e, 0xa1, 0x17,
	0xd0, 0x9c, 0x25, 0x59, 0x48, 0xc3, 0x24, 0xce, 0xda, 0xfa, 0x4e, 0x6d, 0xb7, 0xf5, 0x62, 0x73,
	0x9f, 0xbb, 0xd8, 0xf3, 0xd3, 0x4b, 0x42, 0x07, 0x52, 0x88, 0x4b, 0x35, 0xcb, 0x03, 0xc0, 0x61,
	0x76, 0x79, 0xec, 0x8f, 0x69, 0x92, 0xa2, 0x07, 0xd0, 0x98, 0x72, 0x55, 0xb9, 0xbb, 0x9c, 0x31,
	0xa7, 0xb2, 0x8b, 0x24, 0xa5, 0x6d, 0x7d, 0x47, 0xdb, 0xd5, 0xb0, 0x98, 0x20, 0x04, 0x46, 0x94,
	0xc4, 0x93, 0x76, 0x8d, 0x83, 0x7c, 0x6c, 0xfd, 0xbd, 0x26, 0x0c, 0x62, 0x92, 0xcd, 0x23, 0x8a,
	0xf6, 0xc0, 0x9c, 0xcf, 0x02, 0x9f, 0x92, 0x60, 0x14, 0x4e, 0x49, 0x46, 0xfd, 0xe9, 0x8c, 0x9b,
	0xae, 0xe1, 0x6b, 0x38, 0x3a, 0x82, 0x56, 0x5a, 0xb8, 0x92, 0x07, 0xf0, 0x44, 0x04, 0x50, 0x9a,
	0xdc, 0x2f, 0xdd, 0xcd, 0x9c, 0x98, 0xa6, 0x57, 0x58, 0x5d, 0x85, 0x7e, 0x00, 0xf7, 0x63, 0xf2,
	0x9e, 0x9e, 0x70, 0xe3, 0xe5, 0x9e, 0x35, 0xbe, 0xe7, 0x4d, 0x22, 0xf4, 0x2b, 0x68, 0xcf, 0x52,
	0x12, 0x84, 0x63, 0x4a, 0x02, 0x8f, 0xbc, 0xa7, 0x8a, 0xfd, 0xb6, 0xc1, 0x7d, 0xd8, 0xbf, 0xe6,
	0xc3, 0xe0, 0x96, 0x05, 0xc2, 0xa1, 0x5b, 0xed, 0x6d, 0x0f, 0xc0, 0xac, 0x6a, 0x23, 0x13, 0x6a,
	0x97, 0xe4, 0x4a, 0x26, 0x9c, 0x0d, 0xd1, 0xd3, 0x9c, 0x02, 0x2c, 0xdb, 0xad, 0x17, 0x66, 0xb9,
	0xbd, 0x58, 0x28, 0x49, 0xf1, 0x13, 0xfd, 0xc7, 0xda, 0xf6, 0x2f, 0xe1, 0xd3, 0xaf, 0x75, 0xe6,
	0xdb, 0x99, 0xb7, 0xfe, 0x51, 0x83, 0x7a, 0x3f, 0x0d, 0x48, 0x8a, 0xd6, 0x41, 0x0f, 0x03, 0x69,
	0x46, 0x0f, 0x03, 0x85, 0x2a, 0x7a, 0x95, 0x2a, 0x33, 0xc6, 0x54, 0x9e, 0xf2, 0x26, 0x16, 0x13,
	0xf4, 0x08, 0x8c, 0x2c, 0x0c, 0x48, 0xdb, 0xd8, 0xd1, 0x76, 0xd7, 0x5f, 0x80, 0xd8, 0x72, 0x18,
	0x06, 0x04, 0x73, 0x9c, 0xaf, 0x4a, 0xc3, 0x31, 0x69, 0xd7, 0x77, 0xb4, 0x5d, 0x03, 0x8b, 0x09,
	0x23, 0x58, 0x16, 0xfe, 0x86, 0xb4, 0x1b, 0x1c, 0xe4, 0x63, 0xf4, 0x10, 0x9a, 0x29, 0x99, 0xfa,
	0x61, 0x1c, 0xc6, 0x93, 0xf6, 0x2a, 0x17, 0x94, 0x00, 0xfa, 0x0c, 0x0c, 0x7a, 0x35, 0x23, 0xed,
	0x35, 0xbe, 0x8f, 0x0c, 0x8d, 0x07, 0xb0, 0x3f, 0xba, 0x9a, 0x11, 0xcc, 0xa5, 0xcc, 0xc6, 0x38,
	0x25, 0x8c, 0x7d, 0x36, 0x6d, 0x37, 0x39, 0x35, 0x4a, 0x00, 0xed, 0x41, 0x23, 0xa3, 0x3e, 0x9d,
	0x67, 0x6d, 0xe0, 0x56, 0x90, 0x6a, 0x65, 0xc8, 0x25, 0x58, 0x6a, 0x30, 0x4b, 0xe4, 0xfd, 0x2c,
	0x4c, 0x49, 0x66, 0xd3, 0x76, 0x4b, 0x58, 0x2a, 0x00, 0xe1, 0xeb, 0x39, 0x49, 0x49, 0x3c, 0x26,
	0xed, 0x3b, 0x3c, 0x1f, 0x25, 0x60, 0xed, 0x81, 0xc1, 0x7c, 0x42, 0xab, 0x50, 0x7b, 0x39, 0x3a,
	0x32, 0x57, 0xc4, 0x60, 0x64, 0x6a, 0x6c, 0xe0, 0x78, 0x8e, 0xa9, 0xb3, 0xc1, 0x71, 0xff, 0xb5,
	0x59, 0xb3, 0x5c, 0x68, 0x88, 0x9d, 0x11, 0x40, 0xc3, 0x1e, 0xd3, 0x70, 0x41, 0xcc, 0x15, 0xd4,
	0x82, 0x55, 0x87, 0x6f, 0x16, 0x98, 0x1a, 0xba, 0x0b, 0xcd, 0x23, 0x3f, 0x1e, 0x93, 0x28, 0x22,
	0x81, 0xa9, 0x33, 0xd9, 0x90, 0x26, 0xb3, 0x19, 0x09, 0xcc, 0x1a, 0x5b, 0x74, 0x1c, 0x72, 0x81,
	0x61, 0x1d, 0xc2, 0xa7, 0x3c, 0x14, 0xa9, 0xec, 0xb3, 0x3a, 0x70, 0x94, 0xc4, 0xe7, 0x61, 0x3a,
	0xe5, 0x63, 0xf4, 0x04, 0xea, 0x09, 0x53, 0xe0, 0x87, 0xdd, 0x7a, 0xd1, 0x52, 0xc2, 0xc7, 0x42,
	0x62, 0xfd, 0x59, 0x83, 0x7b, 0xc2, 0xc8, 0x37, 0x5b, 0x88, 0xfe, 0x0f, 0x1a, 0x34, 0xf5, 0x03,
	0x92, 0x5f, 0x6f, 0xa9, 0x33, 0x62, 0x18, 0x96, 0x22, 0x64, 0xc3, 0xd6, 0xcc, 0xcf, 0xb2, 0x70,
	0x41, 0xf8, 0xda, 0xcc, 0x3e, 0x3f, 0x27, 0x8c, 0xdf, 0xed, 0x9a, 0xba, 0x46, 0xd8, 0xbd, 0x59,
	0xd3, 0xfa, 0xad, 0x0e, 0x75, 0x6e, 0xf4, 0x1b, 0xf1, 0x96, 0x33, 0xb0, 0x76, 0x13, 0x03, 0x0d,
	0x85, 0x81, 0x9b, 0x50, 0x3f, 0x9b, 0x5f, 0x91, 0x94, 0x73, 0xb5, 0x89, 0xc5, 0x84, 0xd9, 0xcd,
	0x58, 0xee, 0x53, 0xce, 0xd6, 0x26, 0x96, 0x33, 0xb4, 0x0b, 0x4d, 0x7f, 0x32, 0x49, 0x49, 0x96,
	0x25, 0x29, 0xe7, 0xeb, 0x32, 0xfd, 0x4b, 0x21, 0xda, 0x86, 0xb5, 0xb3, 0xf9, 0x15, 0x0f, 0x84,
	0xf3, 0xb7, 0x89, 0x8b, 0x39, 0x63, 0x12, 0xb3, 0x27, 0x84, 0x4d, 0xc1, 0xa4, 0x02, 0x60, 0x52,
	0x5a, 0x94, 0x3a, 0x10, 0x2c, 0x2c, 0x00, 0xeb, 0x00, 0xd6, 0x78, 0x2a, 0x86, 0x84, 0x2a, 0xf9,
	0xd7, 0x6e, 0xcd, 0xbf, 0x15, 0x03, 0x88, 0x07, 0xa3, 0xe3, 0x53, 0x1f, 0xb5, 0x61, 0xf5, 0x8c,
	0x64, 0xf4, 0x50, 0x66, 0xd1, 0xc0, 0xf9, 0x94, 0x6d, 0xcb, 0x86, 0xfd, 0xf3, 0x73, 0x92, 0xf2,
	0x6c, 0x1a, 0xb8, 0x04, 0xd0, 0x2e, 0x6c, 0x44, 0x7e, 0x46, 0xb9, 0xe9, 0x60, 0xa0, 0xa4, 0xb6,
	0x0a, 0x5b, 0xff, 0xd4, 0xa0, 0x71, 0xe4, 0xc7, 0x41, 0x44, 0x96, 0x23, 0xd1, 0x2a, 0x91, 0xb0,
	0x0c, 0xb1, 0xda, 0xcd, 0x00, 0x79, 0x7a, 0xc5, 0x9c, 0x9d, 0xd4, 0x45, 0x38, 0xb9, 0x90, 0x7b,
	0xf0, 0x31, 0xab, 0x7d, 0x51, 0xf2, 0x4e, 0x1e, 0x1e, 0x1b, 0x32, 0xad, 0x64, 0x46, 0x62, 0x59,
	0x66, 0xf8, 0x98, 0x9d, 0xe7, 0x38, 0x4a, 0xb2, 0xbc, 0xcc, 0x88, 0x09, 0x3b, 0xcf, 0x45, 0x12,
	0xcd, 0xa7, 0x44, 0x16, 0x19, 0x39, 0x43, 0x7b, 0xb0, 0x16, 0xc6, 0x94, 0xa4, 0x0b, 0x3f, 0x92,
	0x55, 0x66, 0x5d, 0xe4, 0xd0, 0x95, 0x28, 0x2e, 0xe4, 0xd6, 0xef, 0x35, 0x00, 0x1e, 0x62, 0x97,
	0x2c, 0x48, 0x54, 0x52, 0x4c, 0x53, 0x29, 0xf6, 0x14, 0xd6, 0xe3, 0xf9, 0xf4, 0x8c, 0xa4, 0xfd,
	0x73, 0x41, 0x62, 0x99, 0xca, 0x0a, 0xaa, 0x38, 0x54, 0xab, 0x38, 0x64, 0x8e, 0xe7, 0xd3, 0x39,
	0xbb, 0xc8, 0x0b, 0xf2, 0x46, 0x68, 0x88, 0x88, 0xaf, 0xe1, 0xd6, 0x25, 0xb4, 0xe4, 0xc9, 0x92,
	0x19, 0xbd, 0x60, 0xd9, 0x28, 0x9b, 0x09, 0xd9, 0x44, 0x58, 0x50, 0x3b, 0x9b, 0x5f, 0xc9, 0xeb,
	0x29, 0x0b, 0x68, 0x19, 0x03, 0x66, 0x42, 0x56, 0x65, 0x19, 0xf9, 0xe4, 0x7d, 0xbc, 0xae, 0xc4,
	0xa5, 0xd6, 0x9f, 0x74, 0x58, 0x5f, 0x6e, 0x3c, 0x6e, 0xed, 0x2f, 0x9e, 0xc2, 0x7a, 0x4a, 0xfc,
	0x28, 0xcc, 0x48, 0x20, 0x23, 0xd0, 0xf9, 0xd9, 0x57, 0x50, 0xb4, 0x03, 0xad, 0x1c, 0x19, 0x78,
	0x5d, 0xf9, 0xaa, 0xab, 0x10, 0x6f, 0x38, 0xe2, 0x8a, 0x2d, 0x43, 0x36, 0x1c, 0x15, 0x1c, 0x7d,
	0x06, 0x77, 0x4b, 0x8c, 0xd9, 0xab, 0x73, 0xc5, 0x65, 0x10, 0x7d, 0x1f, 0xee, 0xf9, 0x0b, 0x92,
	0xfa, 0x13, 0xc2, 0x1f, 0x54, 0xc1, 0x64, 0x41, 0x95, 0xeb, 0x02, 0x66, 0x73, 0x1a, 0xc6, 0xe1,
	0x74, 0x3e, 0xed, 0xf9, 0xe9, 0x24, 0x8c, 0x39, 0x7b, 0x6a, 0x78, 0x19, 0xb4, 0xfe, 0xd6, 0x00,
	0x60, 0xf5, 0x3c, 0xcc, 0x68, 0x38, 0xce, 0x58, 0x58, 0x67, 0x51, 0x32, 0xbe, 0x7c, 0x45, 0xc2,
	0xc9, 0x05, 0x95, 0xf4, 0x50, 0x21, 0x66, 0xf6, 0xcc, 0x1f, 0x5f, 0x46, 0xc9, 0xa4, 0x4b, 0xe2,
	0x09, 0xbd, 0x90, 0x1c, 0x59, 0x06, 0xd1, 0x23, 0x00, 0x9a, 0x50, 0x3f, 0x1a, 0x10, 0x46, 0x23,
	0x41, 0x13, 0x05, 0x61, 0xfb, 0x4c, 0x48, 0x4c, 0xb2, 0x30, 0x63, 0xed, 0x0f, 0xcf, 0x4b, 0x13,
	0xab, 0x10, 0xd3, 0x18, 0xcf, 0xd3, 0x94, 0xc4, 0x94, 0x6b, 0x88, 0x0a, 0xa7, 0x42, 0xec, 0x0e,
	0xb2, 0xe3, 0xe6, 0x62, 0x51, 0xe9, 0x8a, 0x39, 0xfa, 0x6e, 0xf1, 0x72, 0x8a, 0x42, 0x77, 0x4f,
	0x30, 0xe3, 0xe8, 0xc2, 0x0f, 0xe3, 0xca, 0xc3, 0xc9, 0x5c, 0x7d, 0x3f, 0x20, 0xe9, 0x21, 0x0b,
	0x92, 0x5f, 0x24, 0xe6, 0x6a, 0x81, 0x30, 0x46, 0xc8, 0xe4, 0x8e, 0xde, 0x1f, 0x5e, 0x51, 0x92,
	0xf1, 0xaa, 0x67, 0xe0, 0x0a, 0x8a, 0x7e, 0x04, 0x5b, 0x12, 0x11, 0xd7, 0xa4, 0x30, 0x09, 0x5c,
	0xfd, 0x66, 0x21, 0xab, 0x4d, 0xa2, 0xd6, 0x0d, 0x48, 0x3a, 0x24, 0xe3, 0x24, 0x0e, 0xf8, 0xe3,
	0x6d, 0xe0, 0x2a, 0xcc, 0x34, 0x93, 0x7c, 0xad, 0xd4, 0xbc, 0x23, 0x34, 0x2b, 0x30, 0xb2, 0xe0,
	0x0e, 0x4f, 0xb5, 0xa0, 0x7c, 0xd6, 0xbe, 0xcb, 0xd5, 0x96, 0xb0, 0x42, 0x87, 0xf5, 0xf2, 0x21,
	0xc9, 0xda, 0xeb, 0x8a, 0x8e, 0xc4, 0x78, 0xe4, 0xb3, 0xd9, 0x1b, 0x92, 0x66, 0x61, 0x12, 0xbf,
	0xf2, 0xb3, 0x8b, 0xf6, 0x06, 0x4f, 0x73, 0x05, 0x65, 0x19, 0x2c, 0x91, 0xb6, 0xc9, 0x75, 0x14,
	0x84, 0xd5, 0xed, 0x7c, 0x9b, 0x7b, 0x3b, 0xb5, 0xdd, 0x26, 0xce, 0xa7, 0x3c, 0x7a, 0xb6, 0xa3,
	0x3d, 0x25, 0x71, 0x20, 0x9e, 0x14, 0x24, 0xa3, 0x5f, 0x86, 0xd9, 0x6d, 0xe2, 0x90, 0xe8, 0x15,
	0x84, 0xea, 0x7d, 0x51, 0x5b, 0xaa, 0x78, 0xa9, 0xcb, 0x1b, 0x29, 0xa1, 0xbb, 0xa9, 0xea, 0x96,
	0x38, 0xa3, 0x19, 0xc7, 0x64, 0xc1, 0xdb, 0x12, 0x84, 0x57, 0xa0, 0x42, 0x63, 0x24, 0x5e, 0xab,
	0x07, 0x8a, 0x86, 0x80, 0xac, 0xdf, 0xe9, 0x70, 0x67, 0x40, 0xe2, 0x20, 0x8c, 0x27, 0xc5, 0x2b,
	0x58, 0x76, 0x5b, 0x5a, 0xa5, 0xdb, 0x2a, 0x8b, 0xaf, 0xae, 0x16, 0xdf, 0xbc, 0x5f, 0xac, 0x7d,
	0x6d, 0xbf, 0xf8, 0xa1, 0xee, 0x75, 0x1b, 0xd6, 0x44, 0x21, 0x73, 0x3b, 0xf2, 0xca, 0x14, 0xf3,
	0x1b, 0x7b, 0xd8, 0xa2, 0x47, 0x5e, 0x55, 0x7b, 0xe4, 0xb2, 0xef, 0x5c, 0xfb, 0x60, 0xdf, 0x29,
	0xba, 0x9a, 0x66, 0xde, 0xd5, 0x58, 0x7f, 0xd4, 0x60, 0x9d, 0x2b, 0xf2, 0xc3, 0x9b, 0x92, 0x98,
	0xa2, 0x07, 0x65, 0xe3, 0x53, 0x7c, 0x27, 0xea, 0xfc, 0xd5, 0x96, 0x9b, 0xeb, 0x4b, 0x22, 0xe9,
	0xc4, 0xcd, 0x6d, 0xd0, 0xb6, 0xda, 0x06, 0x89, 0x25, 0xe6, 0x4a, 0xd9, 0x90, 0x97, 0x2d, 0x70,
	0xbd, 0xd2, 0x02, 0x5b, 0xff, 0xd1, 0x60, 0x83, 0x3b, 0x36, 0x9c, 0x9f, 0x4d, 0xc3, 0x8c, 0x33,
	0xb3, 0xda, 0x92, 0x95, 0xe9, 0x0b, 0xf2, 0x67, 0x3d, 0x9f, 0xdf, 0xf2, 0x39, 0x51, 0x78, 0x69,
	0xdc, 0xd4, 0xac, 0xd5, 0x95, 0x54, 0xe7, 0x47, 0xd7, 0xb8, 0xe5, 0xe8, 0x72, 0x02, 0xac, 0x7e,
	0xe8, 0x83, 0xa1, 0x8c, 0x71, 0xad, 0x1a, 0xe3, 0x49, 0xde, 0x0c, 0x2b, 0x1d, 0xf5, 0xb7, 0x0f,
	0x92, 0x35, 0xd9, 0xab, 0xf6, 0x78, 0xcc, 0xff, 0x15, 0xa8, 0x5a, 0xdb, 0x84, 0x7a, 0xf2, 0x2e,
	0x96, 0x6d, 0x57, 0x13, 0x8b, 0x09, 0x6f, 0xd5, 0xfc, 0x88, 0x79, 0x21, 0x9f, 0xc6, 0x7c, 0xca,
	0xf4, 0xfd, 0x2c, 0x23, 0x54, 0xd6, 0x7c, 0x31, 0x51, 0x9e, 0xe3, 0xfa, 0xd2, 0x73, 0xfc, 0xff,
	0x32, 0x29, 0x0d, 0xb5, 0x8a, 0x4b, 0x57, 0xca, 0xac, 0x58, 0x3f, 0x83, 0x8d, 0xe3, 0x30, 0xf6,
	0xe3, 0x71, 0xc8, 0x8a, 0x06, 0xf7, 0xf3, 0x01, 0x34, 0x7c, 0x3e, 0x92, 0xcd, 0x9b, 0x9c, 0x95,
	0xfb, 0xeb, 0xca, 0xfe, 0xd6, 0x1f, 0x34, 0x58, 0x1f, 0x12, 0x4a, 0x23, 0x52, 0x74, 0x08, 0x45,
	0x60, 0x9a, 0x1a, 0x58, 0x7e, 0xb2, 0xba, 0x72, 0xb2, 0xcf, 0x8a, 0xad, 0x6a, 0xfc, 0x73, 0x63,
	0x4b, 0xb8, 0x59, 0xf1, 0xa8, 0xf0, 0x20, 0x3f, 0x68, 0x43, 0x3d, 0x68, 0xb1, 0xb9, 0x12, 0xd2,
	0xbf, 0x34, 0xd8, 0x18, 0xa5, 0x7e, 0x9c, 0x9d, 0x93, 0x14, 0x93, 0x5f, 0xcf, 0x49, 0x46, 0xd1,
	0x01, 0xb4, 0xce, 0xd3, 0x64, 0x2a, 0xe3, 0x97, 0x8d, 0xf3, 0xdd, 0xa5, 0xa4, 0x60, 0x55, 0x03,
	0x7d, 0x0f, 0x9a, 0x34, 0xc9, 0xd5, 0xf5, 0x9b, 0xd4, 0x4b, 0xb9, 0x92, 0x31, 0xd9, 0xd6, 0x49,
	0x7f, 0x1f, 0x42, 0x73, 0x1a, 0xc6, 0x22, 0x08, 0x49, 0xf3, 0x12, 0x28, 0xf3, 0x59, 0x57, 0xcf,
	0x73, 0xa9, 0x02, 0x36, 0xaa, 0xdf, 0x9b, 0x7f, 0xd5, 0xa0, 0xd5, 0x25, 0xc1, 0x84, 0xa4, 0xe2,
	0x9f, 0x81, 0x9d, 0x6a, 0x5c, 0xfc, 0xad, 0x57, 0x03, 0x79, 0xb8, 0x1c, 0x08, 0xb7, 0x77, 0x9b,
	0xe7, 0x35, 0xd5, 0xf3, 0xd2, 0x0b, 0xa3, 0x5a, 0x87, 0x91, 0x3c, 0x07, 0xe1, 0x78, 0x71, 0xbd,
	0xca, 0xae, 0xbf, 0x51, 0xfd, 0x7e, 0x19, 0x95, 0x47, 0x72, 0x28, 0xe9, 0xfc, 0x1d, 0x58, 0xf5,
	0x15, 0xb7, 0xaf, 0xe5, 0x37, 0x97, 0xaa, 0x37, 0x42, 0x5f, 0xba, 0x11, 0xd6, 0x02, 0xcc, 0xf2,
	0xa0, 0xb3, 0x59, 0x12, 0x67, 0x04, 0x1d, 0x40, 0x93, 0x4a, 0x2c, 0xff, 0x40, 0x92, 0xe4, 0x57,
	0xf2, 0x86, 0x4b, 0x1d, 0xf4, 0x1c, 0xd6, 0xa4, 0xbd, 0xfc, 0x83, 0x76, 0xab, 0xf8, 0xa0, 0x52,
	0x1d, 0xc6, 0x85, 0xda, 0xde, 0xc7, 0x60, 0xb0, 0xf2, 0xc3, 0x3e, 0xed, 0x0f, 0xe7, 0x57, 0xe6,
	0x0a, 0x5a, 0x03, 0x63, 0x48, 0xa2, 0xc8, 0xd4, 0xf6, 0x6c, 0x58, 0xcb, 0x3f, 0x22, 0x98, 0xd8,
	0x7d, 0xde, 0x13, 0x7f, 0x0a, 0xb8, 0x9f, 0xf7, 0x4c, 0x8d, 0xe9, 0xb9, 0xcf, 0x3f, 0xef, 0x89,
	0x7f, 0x05, 0xdc, 0xe7, 0xaf, 0xcc, 0x1a, 0x1f, 0x7c, 0xf1, 0xca, 0x34, 0x04, 0xd2, 0x31, 0xeb,
	0x7b, 0x7f, 0xd1, 0x01, 0x78, 0x2d, 0x72, 0xd2, 0x34, 0x49, 0xd9, 0x1a, 0xaf, 0xef, 0x39, 0xe6,
	0x0a, 0xda, 0x82, 0x7b, 0xae, 0xf7, 0xc6, 0xee, 0xba, 0x9d, 0xd3, 0x9e, 0x8d, 0x5f, 0x3b, 0xa3,
	0x53, 0xb7, 0x63, 0x6a, 0x68, 0x13, 0xcc, 0x1c, 0xee, 0xe3, 0x8e, 0x83, 0x19, 0xaa, 0xa3, 0x8f,
	0x61, 0x4b, 0xcc, 0xfa, 0x27, 0xa3, 0xd3, 0xfe, 0xf1, 0xe9, 0xd0, 0xf9, 0xf2, 0xc4, 0xf1, 0x8e,
	0x1c, 0xb3, 0x86, 0xb6, 0xe1, 0x41, 0xbe, 0x00, 0x3b, 0x3d, 0xdb, 0xf5, 0x5c, 0xef, 0xe5, 0xe9,
	0xd0, 0xfd, 0xca, 0x31, 0x0d, 0x64, 0xc2, 0x9d, 0x91, 0xdb, 0x73, 0x4e, 0x8f, 0x6d, 0xb7, 0x7b,
	0x82, 0x1d, 0xb3, 0x5e, 0x1a, 0xc2, 0x4e, 0xaf, 0xff, 0xc6, 0xee, 0x16, 0xa2, 0x06, 0x7a, 0x0c,
	0x9f, 0xe4, 0x86, 0x9c, 0x9f, 0x0f, 0x5c, 0x6c, 0x8f, 0xdc, 0xbe, 0x77, 0xda, 0xb1, 0x47, 0x0e,
	0xb3, 0x61, 0xae, 0xa2, 0x4f, 0xe0, 0xa3, 0x65, 0xd7, 0xb0, 0x73, 0xec, 0x60, 0xee, 0xc6, 0x1a,
	0xf3, 0xdb, 0xe9, 0xb8, 0xa3, 0x53, 0xaf, 0x3f, 0x3a, 0xb5, 0xbb, 0xdd, 0xfe, 0x5b, 0xa7, 0x63,
	0x36, 0xd1, 0x47, 0x70, 0x5f, 0xa8, 0xda, 0x3d, 0xc7, 0xeb, 0x14, 0x9b, 0x01, 0xba, 0x0f, 0x1b,
	0x42, 0xc0, 0xf4, 0x8f, 0xfb, 0x27, 0x5e, 0xc7, 0x6c, 0xed, 0xfd, 0x14, 0x5a, 0x4a, 0x67, 0xca,
	0xbc, 0xef, 0xb8, 0xc3, 0xa3, 0xbe, 0xe7, 0x39, 0x47, 0x23, 0xa7, 0x63, 0xae, 0xa0, 0xbb, 0xd0,
	0xc4, 0xce, 0xa0, 0x6b, 0xff, 0xc2, 0xf5, 0x5e, 0xca, 0x3f, 0x58, 0x0a, 0xa9, 0xbe, 0xf7, 0x25,
	0xb4, 0x94, 0x92, 0xc8, 0xa4, 0xae, 0x37, 0x3c, 0xc1, 0x36, 0x73, 0x70, 0x05, 0xad, 0x03, 0x0c,
	0x9d, 0xd1, 0xa8, 0xeb, 0xf4, 0x1c, 0x6f, 0x64, 0x6a, 0x08, 0xa0, 0xd1, 0xb3, 0xf1, 0x4b, 0xd7,
	0x33, 0x75, 0x39, 0x7e, 0xed, 0x8c, 0xcc, 0x1a, 0x6a, 0xc1, 0xea, 0x4b, 0xc7, 0x73, 0xb0, 0xdd,
	0x35, 0x8d, 0xbd, 0xc7, 0x00, 0x65, 0x45, 0x62, 0x87, 0xd7, 0xed, 0x0f, 0x87, 0x82, 0x03, 0x6f,
	0x5d, 0xcf, 0xd4, 0x0e, 0x9f, 0x7c, 0xf5, 0x78, 0x9c, 0x04, 0x84, 0x73, 0x8c, 0xff, 0x71, 0x3c,
	0x4e, 0xa2, 0xfd, 0x50, 0xfc, 0x0f, 0x7d, 0xc0, 0x81, 0xb3, 0x06, 0xff, 0xf9, 0xe1, 0xff, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x18, 0x0c, 0x41, 0xe5, 0xa2, 0x16, 0x00, 0x00,
}
