// Code generated by MockGen. DO NOT EDIT.
// Source: code.vegaprotocol.io/vega/validators/erc20multisig (interfaces: EthereumEventSource)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockEthereumEventSource is a mock of EthereumEventSource interface.
type MockEthereumEventSource struct {
	ctrl     *gomock.Controller
	recorder *MockEthereumEventSourceMockRecorder
}

// MockEthereumEventSourceMockRecorder is the mock recorder for MockEthereumEventSource.
type MockEthereumEventSourceMockRecorder struct {
	mock *MockEthereumEventSource
}

// NewMockEthereumEventSource creates a new mock instance.
func NewMockEthereumEventSource(ctrl *gomock.Controller) *MockEthereumEventSource {
	mock := &MockEthereumEventSource{ctrl: ctrl}
	mock.recorder = &MockEthereumEventSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEthereumEventSource) EXPECT() *MockEthereumEventSourceMockRecorder {
	return m.recorder
}

// UpdateMultisigControlLastBlockSeen mocks base method.
func (m *MockEthereumEventSource) UpdateMultisigControlLastBlockSeen(arg0 uint64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateMultisigControlLastBlockSeen", arg0)
}

// UpdateMultisigControlLastBlockSeen indicates an expected call of UpdateMultisigControlLastBlockSeen.
func (mr *MockEthereumEventSourceMockRecorder) UpdateMultisigControlLastBlockSeen(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMultisigControlLastBlockSeen", reflect.TypeOf((*MockEthereumEventSource)(nil).UpdateMultisigControlLastBlockSeen), arg0)
}
