// Code generated by protoc-gen-go. DO NOT EDIT.
// source: vega/scenariorunner/core/instructions.proto

package core

import (
	proto1 "code.vegaprotocol.io/vega/proto"
	api "code.vegaprotocol.io/vega/proto/api"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	duration "github.com/golang/protobuf/ptypes/duration"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestType int32

const (
	RequestType_SET_TIME              RequestType = 0
	RequestType_ADVANCE_TIME          RequestType = 1
	RequestType_MARKET_SUMMARY        RequestType = 2
	RequestType_SUMMARY               RequestType = 3
	RequestType_SUBMIT_ORDER          RequestType = 100
	RequestType_CANCEL_ORDER          RequestType = 101
	RequestType_AMEND_ORDER           RequestType = 102
	RequestType_NOTIFY_TRADER_ACCOUNT RequestType = 103
	RequestType_WITHDRAW              RequestType = 104
	// orders
	RequestType_ORDERS_BY_MARKET       RequestType = 200
	RequestType_ORDERS_BY_PARTY        RequestType = 201
	RequestType_ORDER_BY_MARKET_AND_ID RequestType = 202
	RequestType_ORDER_BY_REFERENCE     RequestType = 203
	// markets
	RequestType_MARKET_BY_ID RequestType = 210
	RequestType_MARKETS      RequestType = 211
	RequestType_MARKET_DEPTH RequestType = 212
	RequestType_LAST_TRADE   RequestType = 213
	// parties
	RequestType_PARTY_BY_ID RequestType = 220
	RequestType_PARTIES     RequestType = 221
	// trades
	RequestType_TRADES_BY_MARKET RequestType = 230
	RequestType_TRADES_BY_PARTY  RequestType = 231
	RequestType_TRADES_BY_ORDER  RequestType = 232
	// positions
	RequestType_POSITIONS_BY_PARTY RequestType = 240
	// candles
	RequestType_CANDLES RequestType = 250
	// accounts
	RequestType_ACCOUNTS_BY_PARTY            RequestType = 260
	RequestType_ACCOUNTS_BY_PARTY_AND_MARKET RequestType = 261
	RequestType_ACCOUNTS_BY_PARTY_AND_TYPE   RequestType = 262
	RequestType_ACCOUNTS_BY_PARTY_AND_ASSET  RequestType = 263
)

var RequestType_name = map[int32]string{
	0:   "SET_TIME",
	1:   "ADVANCE_TIME",
	2:   "MARKET_SUMMARY",
	3:   "SUMMARY",
	100: "SUBMIT_ORDER",
	101: "CANCEL_ORDER",
	102: "AMEND_ORDER",
	103: "NOTIFY_TRADER_ACCOUNT",
	104: "WITHDRAW",
	200: "ORDERS_BY_MARKET",
	201: "ORDERS_BY_PARTY",
	202: "ORDER_BY_MARKET_AND_ID",
	203: "ORDER_BY_REFERENCE",
	210: "MARKET_BY_ID",
	211: "MARKETS",
	212: "MARKET_DEPTH",
	213: "LAST_TRADE",
	220: "PARTY_BY_ID",
	221: "PARTIES",
	230: "TRADES_BY_MARKET",
	231: "TRADES_BY_PARTY",
	232: "TRADES_BY_ORDER",
	240: "POSITIONS_BY_PARTY",
	250: "CANDLES",
	260: "ACCOUNTS_BY_PARTY",
	261: "ACCOUNTS_BY_PARTY_AND_MARKET",
	262: "ACCOUNTS_BY_PARTY_AND_TYPE",
	263: "ACCOUNTS_BY_PARTY_AND_ASSET",
}

var RequestType_value = map[string]int32{
	"SET_TIME":                     0,
	"ADVANCE_TIME":                 1,
	"MARKET_SUMMARY":               2,
	"SUMMARY":                      3,
	"SUBMIT_ORDER":                 100,
	"CANCEL_ORDER":                 101,
	"AMEND_ORDER":                  102,
	"NOTIFY_TRADER_ACCOUNT":        103,
	"WITHDRAW":                     104,
	"ORDERS_BY_MARKET":             200,
	"ORDERS_BY_PARTY":              201,
	"ORDER_BY_MARKET_AND_ID":       202,
	"ORDER_BY_REFERENCE":           203,
	"MARKET_BY_ID":                 210,
	"MARKETS":                      211,
	"MARKET_DEPTH":                 212,
	"LAST_TRADE":                   213,
	"PARTY_BY_ID":                  220,
	"PARTIES":                      221,
	"TRADES_BY_MARKET":             230,
	"TRADES_BY_PARTY":              231,
	"TRADES_BY_ORDER":              232,
	"POSITIONS_BY_PARTY":           240,
	"CANDLES":                      250,
	"ACCOUNTS_BY_PARTY":            260,
	"ACCOUNTS_BY_PARTY_AND_MARKET": 261,
	"ACCOUNTS_BY_PARTY_AND_TYPE":   262,
	"ACCOUNTS_BY_PARTY_AND_ASSET":  263,
}

func (x RequestType) String() string {
	return proto.EnumName(RequestType_name, int32(x))
}

func (RequestType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_eeabd909e3161f6f, []int{0}
}

type Instruction struct {
	Description          string      `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Request              RequestType `protobuf:"varint,2,opt,name=request,proto3,enum=core.RequestType" json:"request,omitempty"`
	Message              *any.Any    `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Instruction) Reset()         { *m = Instruction{} }
func (m *Instruction) String() string { return proto.CompactTextString(m) }
func (*Instruction) ProtoMessage()    {}
func (*Instruction) Descriptor() ([]byte, []int) {
	return fileDescriptor_eeabd909e3161f6f, []int{0}
}

func (m *Instruction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Instruction.Unmarshal(m, b)
}
func (m *Instruction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Instruction.Marshal(b, m, deterministic)
}
func (m *Instruction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Instruction.Merge(m, src)
}
func (m *Instruction) XXX_Size() int {
	return xxx_messageInfo_Instruction.Size(m)
}
func (m *Instruction) XXX_DiscardUnknown() {
	xxx_messageInfo_Instruction.DiscardUnknown(m)
}

var xxx_messageInfo_Instruction proto.InternalMessageInfo

func (m *Instruction) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Instruction) GetRequest() RequestType {
	if m != nil {
		return m.Request
	}
	return RequestType_SET_TIME
}

func (m *Instruction) GetMessage() *any.Any {
	if m != nil {
		return m.Message
	}
	return nil
}

type InstructionSet struct {
	Description          string         `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Instructions         []*Instruction `protobuf:"bytes,2,rep,name=instructions,proto3" json:"instructions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *InstructionSet) Reset()         { *m = InstructionSet{} }
func (m *InstructionSet) String() string { return proto.CompactTextString(m) }
func (*InstructionSet) ProtoMessage()    {}
func (*InstructionSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_eeabd909e3161f6f, []int{1}
}

func (m *InstructionSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstructionSet.Unmarshal(m, b)
}
func (m *InstructionSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstructionSet.Marshal(b, m, deterministic)
}
func (m *InstructionSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstructionSet.Merge(m, src)
}
func (m *InstructionSet) XXX_Size() int {
	return xxx_messageInfo_InstructionSet.Size(m)
}
func (m *InstructionSet) XXX_DiscardUnknown() {
	xxx_messageInfo_InstructionSet.DiscardUnknown(m)
}

var xxx_messageInfo_InstructionSet proto.InternalMessageInfo

func (m *InstructionSet) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *InstructionSet) GetInstructions() []*Instruction {
	if m != nil {
		return m.Instructions
	}
	return nil
}

type InstructionResult struct {
	Instruction          *Instruction `protobuf:"bytes,1,opt,name=instruction,proto3" json:"instruction,omitempty"`
	Error                string       `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Response             *any.Any     `protobuf:"bytes,3,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *InstructionResult) Reset()         { *m = InstructionResult{} }
func (m *InstructionResult) String() string { return proto.CompactTextString(m) }
func (*InstructionResult) ProtoMessage()    {}
func (*InstructionResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_eeabd909e3161f6f, []int{2}
}

func (m *InstructionResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstructionResult.Unmarshal(m, b)
}
func (m *InstructionResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstructionResult.Marshal(b, m, deterministic)
}
func (m *InstructionResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstructionResult.Merge(m, src)
}
func (m *InstructionResult) XXX_Size() int {
	return xxx_messageInfo_InstructionResult.Size(m)
}
func (m *InstructionResult) XXX_DiscardUnknown() {
	xxx_messageInfo_InstructionResult.DiscardUnknown(m)
}

var xxx_messageInfo_InstructionResult proto.InternalMessageInfo

func (m *InstructionResult) GetInstruction() *Instruction {
	if m != nil {
		return m.Instruction
	}
	return nil
}

func (m *InstructionResult) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *InstructionResult) GetResponse() *any.Any {
	if m != nil {
		return m.Response
	}
	return nil
}

type Metadata struct {
	InstructionsProcessed uint64                `protobuf:"varint,1,opt,name=instructionsProcessed,proto3" json:"instructionsProcessed,omitempty"`
	InstructionsOmitted   uint64                `protobuf:"varint,2,opt,name=instructionsOmitted,proto3" json:"instructionsOmitted,omitempty"`
	TradesGenerated       uint64                `protobuf:"varint,3,opt,name=tradesGenerated,proto3" json:"tradesGenerated,omitempty"`
	ProcessingTime        *duration.Duration    `protobuf:"bytes,5,opt,name=processingTime,proto3" json:"processingTime,omitempty"`
	FinalMarketDepth      []*proto1.MarketDepth `protobuf:"bytes,6,rep,name=finalMarketDepth,proto3" json:"finalMarketDepth,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}              `json:"-"`
	XXX_unrecognized      []byte                `json:"-"`
	XXX_sizecache         int32                 `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_eeabd909e3161f6f, []int{3}
}

func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata.Unmarshal(m, b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
}
func (m *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(m, src)
}
func (m *Metadata) XXX_Size() int {
	return xxx_messageInfo_Metadata.Size(m)
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetInstructionsProcessed() uint64 {
	if m != nil {
		return m.InstructionsProcessed
	}
	return 0
}

func (m *Metadata) GetInstructionsOmitted() uint64 {
	if m != nil {
		return m.InstructionsOmitted
	}
	return 0
}

func (m *Metadata) GetTradesGenerated() uint64 {
	if m != nil {
		return m.TradesGenerated
	}
	return 0
}

func (m *Metadata) GetProcessingTime() *duration.Duration {
	if m != nil {
		return m.ProcessingTime
	}
	return nil
}

func (m *Metadata) GetFinalMarketDepth() []*proto1.MarketDepth {
	if m != nil {
		return m.FinalMarketDepth
	}
	return nil
}

type ResultSet struct {
	Metadata             *Metadata            `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Results              []*InstructionResult `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	InitialState         *Summary             `protobuf:"bytes,3,opt,name=initialState,proto3" json:"initialState,omitempty"`
	FinalState           *Summary             `protobuf:"bytes,4,opt,name=finalState,proto3" json:"finalState,omitempty"`
	Config               *Config              `protobuf:"bytes,5,opt,name=config,proto3" json:"config,omitempty"`
	Version              string               `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ResultSet) Reset()         { *m = ResultSet{} }
func (m *ResultSet) String() string { return proto.CompactTextString(m) }
func (*ResultSet) ProtoMessage()    {}
func (*ResultSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_eeabd909e3161f6f, []int{4}
}

func (m *ResultSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResultSet.Unmarshal(m, b)
}
func (m *ResultSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResultSet.Marshal(b, m, deterministic)
}
func (m *ResultSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResultSet.Merge(m, src)
}
func (m *ResultSet) XXX_Size() int {
	return xxx_messageInfo_ResultSet.Size(m)
}
func (m *ResultSet) XXX_DiscardUnknown() {
	xxx_messageInfo_ResultSet.DiscardUnknown(m)
}

var xxx_messageInfo_ResultSet proto.InternalMessageInfo

func (m *ResultSet) GetMetadata() *Metadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *ResultSet) GetResults() []*InstructionResult {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *ResultSet) GetInitialState() *Summary {
	if m != nil {
		return m.InitialState
	}
	return nil
}

func (m *ResultSet) GetFinalState() *Summary {
	if m != nil {
		return m.FinalState
	}
	return nil
}

func (m *ResultSet) GetConfig() *Config {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *ResultSet) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type SummaryResponse struct {
	Summary              *Summary `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SummaryResponse) Reset()         { *m = SummaryResponse{} }
func (m *SummaryResponse) String() string { return proto.CompactTextString(m) }
func (*SummaryResponse) ProtoMessage()    {}
func (*SummaryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eeabd909e3161f6f, []int{5}
}

func (m *SummaryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SummaryResponse.Unmarshal(m, b)
}
func (m *SummaryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SummaryResponse.Marshal(b, m, deterministic)
}
func (m *SummaryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SummaryResponse.Merge(m, src)
}
func (m *SummaryResponse) XXX_Size() int {
	return xxx_messageInfo_SummaryResponse.Size(m)
}
func (m *SummaryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SummaryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SummaryResponse proto.InternalMessageInfo

func (m *SummaryResponse) GetSummary() *Summary {
	if m != nil {
		return m.Summary
	}
	return nil
}

type Summary struct {
	Markets              []*MarketSummary `protobuf:"bytes,1,rep,name=markets,proto3" json:"markets,omitempty"`
	Parties              []*PartySummary  `protobuf:"bytes,2,rep,name=parties,proto3" json:"parties,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Summary) Reset()         { *m = Summary{} }
func (m *Summary) String() string { return proto.CompactTextString(m) }
func (*Summary) ProtoMessage()    {}
func (*Summary) Descriptor() ([]byte, []int) {
	return fileDescriptor_eeabd909e3161f6f, []int{6}
}

func (m *Summary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Summary.Unmarshal(m, b)
}
func (m *Summary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Summary.Marshal(b, m, deterministic)
}
func (m *Summary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Summary.Merge(m, src)
}
func (m *Summary) XXX_Size() int {
	return xxx_messageInfo_Summary.Size(m)
}
func (m *Summary) XXX_DiscardUnknown() {
	xxx_messageInfo_Summary.DiscardUnknown(m)
}

var xxx_messageInfo_Summary proto.InternalMessageInfo

func (m *Summary) GetMarkets() []*MarketSummary {
	if m != nil {
		return m.Markets
	}
	return nil
}

func (m *Summary) GetParties() []*PartySummary {
	if m != nil {
		return m.Parties
	}
	return nil
}

type Config struct {
	InitialTime                 *timestamp.Timestamp `protobuf:"bytes,1,opt,name=initialTime,proto3" json:"initialTime,omitempty"`
	AdvanceTimeAfterInstruction bool                 `protobuf:"varint,2,opt,name=advanceTimeAfterInstruction,proto3" json:"advanceTimeAfterInstruction,omitempty"`
	TimeDelta                   *duration.Duration   `protobuf:"bytes,3,opt,name=timeDelta,proto3" json:"timeDelta,omitempty"`
	OmitUnsupportedInstructions bool                 `protobuf:"varint,4,opt,name=omitUnsupportedInstructions,proto3" json:"omitUnsupportedInstructions,omitempty"`
	OmitInvalidInstructions     bool                 `protobuf:"varint,5,opt,name=omitInvalidInstructions,proto3" json:"omitInvalidInstructions,omitempty"`
	XXX_NoUnkeyedLiteral        struct{}             `json:"-"`
	XXX_unrecognized            []byte               `json:"-"`
	XXX_sizecache               int32                `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_eeabd909e3161f6f, []int{7}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetInitialTime() *timestamp.Timestamp {
	if m != nil {
		return m.InitialTime
	}
	return nil
}

func (m *Config) GetAdvanceTimeAfterInstruction() bool {
	if m != nil {
		return m.AdvanceTimeAfterInstruction
	}
	return false
}

func (m *Config) GetTimeDelta() *duration.Duration {
	if m != nil {
		return m.TimeDelta
	}
	return nil
}

func (m *Config) GetOmitUnsupportedInstructions() bool {
	if m != nil {
		return m.OmitUnsupportedInstructions
	}
	return false
}

func (m *Config) GetOmitInvalidInstructions() bool {
	if m != nil {
		return m.OmitInvalidInstructions
	}
	return false
}

type MarketSummaryResponse struct {
	Summary              *MarketSummary `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *MarketSummaryResponse) Reset()         { *m = MarketSummaryResponse{} }
func (m *MarketSummaryResponse) String() string { return proto.CompactTextString(m) }
func (*MarketSummaryResponse) ProtoMessage()    {}
func (*MarketSummaryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eeabd909e3161f6f, []int{8}
}

func (m *MarketSummaryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarketSummaryResponse.Unmarshal(m, b)
}
func (m *MarketSummaryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarketSummaryResponse.Marshal(b, m, deterministic)
}
func (m *MarketSummaryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarketSummaryResponse.Merge(m, src)
}
func (m *MarketSummaryResponse) XXX_Size() int {
	return xxx_messageInfo_MarketSummaryResponse.Size(m)
}
func (m *MarketSummaryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MarketSummaryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MarketSummaryResponse proto.InternalMessageInfo

func (m *MarketSummaryResponse) GetSummary() *MarketSummary {
	if m != nil {
		return m.Summary
	}
	return nil
}

type SummaryRequest struct {
	Pagination           *api.Pagination `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *SummaryRequest) Reset()         { *m = SummaryRequest{} }
func (m *SummaryRequest) String() string { return proto.CompactTextString(m) }
func (*SummaryRequest) ProtoMessage()    {}
func (*SummaryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eeabd909e3161f6f, []int{9}
}

func (m *SummaryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SummaryRequest.Unmarshal(m, b)
}
func (m *SummaryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SummaryRequest.Marshal(b, m, deterministic)
}
func (m *SummaryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SummaryRequest.Merge(m, src)
}
func (m *SummaryRequest) XXX_Size() int {
	return xxx_messageInfo_SummaryRequest.Size(m)
}
func (m *SummaryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SummaryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SummaryRequest proto.InternalMessageInfo

func (m *SummaryRequest) GetPagination() *api.Pagination {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type MarketSummaryRequest struct {
	MarketID             string          `protobuf:"bytes,1,opt,name=marketID,proto3" json:"marketID,omitempty"`
	Pagination           *api.Pagination `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *MarketSummaryRequest) Reset()         { *m = MarketSummaryRequest{} }
func (m *MarketSummaryRequest) String() string { return proto.CompactTextString(m) }
func (*MarketSummaryRequest) ProtoMessage()    {}
func (*MarketSummaryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eeabd909e3161f6f, []int{10}
}

func (m *MarketSummaryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarketSummaryRequest.Unmarshal(m, b)
}
func (m *MarketSummaryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarketSummaryRequest.Marshal(b, m, deterministic)
}
func (m *MarketSummaryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarketSummaryRequest.Merge(m, src)
}
func (m *MarketSummaryRequest) XXX_Size() int {
	return xxx_messageInfo_MarketSummaryRequest.Size(m)
}
func (m *MarketSummaryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MarketSummaryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MarketSummaryRequest proto.InternalMessageInfo

func (m *MarketSummaryRequest) GetMarketID() string {
	if m != nil {
		return m.MarketID
	}
	return ""
}

func (m *MarketSummaryRequest) GetPagination() *api.Pagination {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type MarketSummary struct {
	Market               *proto1.Market      `protobuf:"bytes,1,opt,name=market,proto3" json:"market,omitempty"`
	Trades               []*proto1.Trade     `protobuf:"bytes,3,rep,name=trades,proto3" json:"trades,omitempty"`
	Orders               []*proto1.Order     `protobuf:"bytes,4,rep,name=orders,proto3" json:"orders,omitempty"`
	MarketDepth          *proto1.MarketDepth `protobuf:"bytes,5,opt,name=marketDepth,proto3" json:"marketDepth,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *MarketSummary) Reset()         { *m = MarketSummary{} }
func (m *MarketSummary) String() string { return proto.CompactTextString(m) }
func (*MarketSummary) ProtoMessage()    {}
func (*MarketSummary) Descriptor() ([]byte, []int) {
	return fileDescriptor_eeabd909e3161f6f, []int{11}
}

func (m *MarketSummary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarketSummary.Unmarshal(m, b)
}
func (m *MarketSummary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarketSummary.Marshal(b, m, deterministic)
}
func (m *MarketSummary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarketSummary.Merge(m, src)
}
func (m *MarketSummary) XXX_Size() int {
	return xxx_messageInfo_MarketSummary.Size(m)
}
func (m *MarketSummary) XXX_DiscardUnknown() {
	xxx_messageInfo_MarketSummary.DiscardUnknown(m)
}

var xxx_messageInfo_MarketSummary proto.InternalMessageInfo

func (m *MarketSummary) GetMarket() *proto1.Market {
	if m != nil {
		return m.Market
	}
	return nil
}

func (m *MarketSummary) GetTrades() []*proto1.Trade {
	if m != nil {
		return m.Trades
	}
	return nil
}

func (m *MarketSummary) GetOrders() []*proto1.Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

func (m *MarketSummary) GetMarketDepth() *proto1.MarketDepth {
	if m != nil {
		return m.MarketDepth
	}
	return nil
}

type PartySummary struct {
	Party                *proto1.Party     `protobuf:"bytes,1,opt,name=party,proto3" json:"party,omitempty"`
	Accounts             []*proto1.Account `protobuf:"bytes,2,rep,name=accounts,proto3" json:"accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PartySummary) Reset()         { *m = PartySummary{} }
func (m *PartySummary) String() string { return proto.CompactTextString(m) }
func (*PartySummary) ProtoMessage()    {}
func (*PartySummary) Descriptor() ([]byte, []int) {
	return fileDescriptor_eeabd909e3161f6f, []int{12}
}

func (m *PartySummary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PartySummary.Unmarshal(m, b)
}
func (m *PartySummary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PartySummary.Marshal(b, m, deterministic)
}
func (m *PartySummary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartySummary.Merge(m, src)
}
func (m *PartySummary) XXX_Size() int {
	return xxx_messageInfo_PartySummary.Size(m)
}
func (m *PartySummary) XXX_DiscardUnknown() {
	xxx_messageInfo_PartySummary.DiscardUnknown(m)
}

var xxx_messageInfo_PartySummary proto.InternalMessageInfo

func (m *PartySummary) GetParty() *proto1.Party {
	if m != nil {
		return m.Party
	}
	return nil
}

func (m *PartySummary) GetAccounts() []*proto1.Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

func init() {
	proto.RegisterEnum("core.RequestType", RequestType_name, RequestType_value)
	proto.RegisterType((*Instruction)(nil), "core.Instruction")
	proto.RegisterType((*InstructionSet)(nil), "core.InstructionSet")
	proto.RegisterType((*InstructionResult)(nil), "core.InstructionResult")
	proto.RegisterType((*Metadata)(nil), "core.Metadata")
	proto.RegisterType((*ResultSet)(nil), "core.ResultSet")
	proto.RegisterType((*SummaryResponse)(nil), "core.SummaryResponse")
	proto.RegisterType((*Summary)(nil), "core.Summary")
	proto.RegisterType((*Config)(nil), "core.Config")
	proto.RegisterType((*MarketSummaryResponse)(nil), "core.MarketSummaryResponse")
	proto.RegisterType((*SummaryRequest)(nil), "core.SummaryRequest")
	proto.RegisterType((*MarketSummaryRequest)(nil), "core.MarketSummaryRequest")
	proto.RegisterType((*MarketSummary)(nil), "core.MarketSummary")
	proto.RegisterType((*PartySummary)(nil), "core.PartySummary")
}

func init() {
	proto.RegisterFile("vega/scenariorunner/core/instructions.proto", fileDescriptor_eeabd909e3161f6f)
}

var fileDescriptor_eeabd909e3161f6f = []byte{
	// 1204 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0xcb, 0x6f, 0x1b, 0xd5,
	0x17, 0xfe, 0x8d, 0xf3, 0xb0, 0x73, 0xec, 0x26, 0x93, 0xd3, 0xa4, 0x75, 0xd3, 0xea, 0xd7, 0xd4,
	0x20, 0x11, 0x5a, 0x6a, 0xf7, 0x01, 0x02, 0x21, 0x90, 0x98, 0x7a, 0xa6, 0xd4, 0xa2, 0x7e, 0xe8,
	0xce, 0x84, 0x2a, 0x12, 0x92, 0x75, 0x6b, 0xdf, 0xb8, 0x23, 0xe2, 0x99, 0xe1, 0xce, 0x38, 0x52,
	0xf6, 0x3c, 0x36, 0x5d, 0xf0, 0x17, 0xf0, 0x57, 0xb0, 0x65, 0xcf, 0x63, 0xc7, 0x63, 0x57, 0xb6,
	0xc0, 0x92, 0x35, 0x2b, 0x74, 0x1f, 0xe3, 0xdc, 0xd8, 0x26, 0xb0, 0xf3, 0xfd, 0xbe, 0xef, 0xbc,
	0x8f, 0xcf, 0xc0, 0xad, 0x63, 0x36, 0xa2, 0x8d, 0x74, 0xc0, 0x22, 0xca, 0xc3, 0x98, 0x4f, 0xa2,
	0x88, 0xf1, 0xc6, 0x20, 0xe6, 0xac, 0x11, 0x46, 0x69, 0xc6, 0x27, 0x83, 0x2c, 0x8c, 0xa3, 0xb4,
	0x9e, 0xf0, 0x38, 0x8b, 0x71, 0x59, 0x10, 0x3b, 0xff, 0x1f, 0xc5, 0xf1, 0xe8, 0x88, 0x35, 0x24,
	0xf6, 0x74, 0x72, 0xd8, 0x18, 0x4e, 0x38, 0x15, 0x32, 0xa5, 0xda, 0xb9, 0x32, 0xcb, 0xd3, 0xe8,
	0x44, 0x53, 0xdb, 0x32, 0x9a, 0xfc, 0xdd, 0x10, 0x3f, 0x35, 0x5c, 0x35, 0xe0, 0x31, 0xe5, 0x1f,
	0xb3, 0x4c, 0x47, 0xdc, 0xb9, 0x66, 0x30, 0x34, 0x09, 0x1b, 0x19, 0xa7, 0xc3, 0x30, 0x1a, 0x69,
	0xf6, 0xfa, 0x6c, 0xa4, 0x2c, 0x1c, 0xb3, 0x34, 0xa3, 0xe3, 0x44, 0x09, 0x6a, 0xcf, 0x2d, 0x28,
	0xb7, 0x4e, 0xeb, 0xc0, 0x5d, 0x28, 0x0f, 0x59, 0x3a, 0xe0, 0x61, 0x22, 0x9e, 0x55, 0x6b, 0xd7,
	0xda, 0x5b, 0x23, 0x26, 0x84, 0xb7, 0xa0, 0xc8, 0xd9, 0x27, 0x13, 0x96, 0x66, 0xd5, 0xc2, 0xae,
	0xb5, 0xb7, 0x7e, 0x6f, 0xb3, 0x2e, 0x8a, 0xae, 0x13, 0x05, 0x06, 0x27, 0x09, 0x23, 0xb9, 0x02,
	0xeb, 0x50, 0x1c, 0xb3, 0x34, 0xa5, 0x23, 0x56, 0x5d, 0xda, 0xb5, 0xf6, 0xca, 0xf7, 0xb6, 0xea,
	0x2a, 0xa3, 0x7a, 0x9e, 0x51, 0xdd, 0x89, 0x4e, 0x48, 0x2e, 0xaa, 0x85, 0xb0, 0x6e, 0x64, 0xe3,
	0xb3, 0xec, 0x3f, 0x24, 0xf4, 0x06, 0x54, 0xcc, 0x49, 0x54, 0x0b, 0xbb, 0x4b, 0x7b, 0xe5, 0x3c,
	0x2b, 0xc3, 0x1b, 0x39, 0x23, 0xab, 0x7d, 0x69, 0xc1, 0xa6, 0xc9, 0xb2, 0x74, 0x72, 0x94, 0xe1,
	0x7d, 0x28, 0x1b, 0x2a, 0x19, 0x6e, 0xa1, 0x2f, 0x53, 0x85, 0x5b, 0xb0, 0xc2, 0x38, 0x8f, 0xb9,
	0x6c, 0xc8, 0x1a, 0x51, 0x0f, 0xbc, 0x03, 0x25, 0xce, 0xd2, 0x24, 0x8e, 0xd2, 0xf3, 0x8b, 0x9f,
	0xaa, 0x6a, 0x5f, 0x15, 0xa0, 0xd4, 0x66, 0x19, 0x1d, 0xd2, 0x8c, 0xe2, 0xeb, 0xb0, 0x6d, 0xe6,
	0xdb, 0xe3, 0xf1, 0x80, 0xa5, 0x29, 0x1b, 0xca, 0x9c, 0x96, 0xc9, 0x62, 0x12, 0xef, 0xc0, 0x45,
	0x93, 0xe8, 0x8e, 0xc3, 0x2c, 0x63, 0x43, 0x99, 0xd8, 0x32, 0x59, 0x44, 0xe1, 0x1e, 0x6c, 0x88,
	0x9d, 0x61, 0xe9, 0xfb, 0x2c, 0x62, 0x9c, 0x0a, 0xf5, 0x92, 0x54, 0xcf, 0xc2, 0xe8, 0xc0, 0x7a,
	0xa2, 0x02, 0x85, 0xd1, 0x28, 0x08, 0xc7, 0xac, 0xba, 0x22, 0xcb, 0xba, 0x32, 0x57, 0x96, 0xab,
	0xf7, 0x9d, 0xcc, 0x18, 0xe0, 0xbb, 0x60, 0x1f, 0x86, 0x11, 0x3d, 0x6a, 0xcb, 0x1d, 0x76, 0x59,
	0x92, 0x3d, 0xab, 0xae, 0xea, 0x79, 0xc9, 0x75, 0x37, 0x08, 0x32, 0x27, 0xad, 0x3d, 0x2f, 0xc0,
	0x9a, 0x1a, 0x94, 0x58, 0x8d, 0x9b, 0x50, 0x1a, 0xeb, 0x6e, 0xe9, 0x41, 0xad, 0xab, 0x41, 0xe5,
	0x3d, 0x24, 0x53, 0x1e, 0xef, 0x8a, 0xad, 0x15, 0x86, 0xf9, 0x7e, 0x5c, 0x9e, 0x9f, 0xa9, 0xe4,
	0x49, 0xae, 0xc3, 0xbb, 0x62, 0xaf, 0xc2, 0x2c, 0xa4, 0x47, 0x7e, 0x46, 0xb3, 0x7c, 0x86, 0x17,
	0x94, 0x9d, 0x3f, 0x19, 0x8f, 0x29, 0x3f, 0x21, 0x67, 0x24, 0x78, 0x1b, 0x40, 0xe6, 0xac, 0x0c,
	0x96, 0x17, 0x19, 0x18, 0x02, 0x7c, 0x19, 0x56, 0x07, 0x71, 0x74, 0x18, 0x8e, 0x74, 0x23, 0x2b,
	0x4a, 0xda, 0x94, 0x18, 0xd1, 0x1c, 0x56, 0xa1, 0x78, 0xcc, 0x78, 0x2a, 0xd6, 0x71, 0x55, 0xee,
	0x57, 0xfe, 0xac, 0xbd, 0x0d, 0x1b, 0xb9, 0x5b, 0xbd, 0x42, 0xf8, 0x0a, 0x14, 0x53, 0x05, 0xe9,
	0x96, 0xcc, 0x84, 0xcf, 0xd9, 0xda, 0x21, 0x14, 0x35, 0x86, 0xb7, 0xa1, 0xa8, 0x6f, 0x4a, 0xd5,
	0x92, 0xbd, 0xb9, 0xa8, 0xdb, 0x28, 0xc1, 0xa9, 0xa5, 0xd6, 0xe0, 0x6b, 0x50, 0x4c, 0x28, 0xcf,
	0x42, 0x96, 0xb7, 0x12, 0x95, 0xbc, 0x47, 0x79, 0x76, 0x32, 0x55, 0x6b, 0x49, 0xed, 0x9b, 0x02,
	0xac, 0xaa, 0x82, 0xf0, 0x1d, 0xf1, 0xdf, 0x92, 0xdd, 0x92, 0xcb, 0xa3, 0xf2, 0xdb, 0x99, 0x5b,
	0x9e, 0x20, 0x3f, 0x51, 0xc4, 0x94, 0xe3, 0x7b, 0x70, 0x95, 0x0e, 0x8f, 0x69, 0x34, 0x60, 0xe2,
	0xe9, 0x1c, 0x66, 0x8c, 0x1b, 0xc3, 0x93, 0x1b, 0x5e, 0x22, 0xe7, 0x49, 0xf0, 0x4d, 0x58, 0x13,
	0xe7, 0xcf, 0x65, 0x47, 0x19, 0xd5, 0xd3, 0x3c, 0x67, 0x75, 0x4f, 0xb5, 0x22, 0x74, 0x3c, 0x0e,
	0xb3, 0xfd, 0x28, 0x9d, 0x24, 0x49, 0xcc, 0x33, 0x36, 0x6c, 0x99, 0x07, 0x67, 0x59, 0x85, 0x3e,
	0x47, 0x82, 0x6f, 0xc1, 0x65, 0x41, 0xb7, 0xa2, 0x63, 0x7a, 0x14, 0x9e, 0xb5, 0x5e, 0x91, 0xd6,
	0xff, 0x44, 0xd7, 0x1e, 0xc2, 0xf6, 0xd9, 0x39, 0xe4, 0x93, 0xbe, 0x3d, 0x3b, 0xe9, 0xc5, 0x53,
	0xcb, 0xe7, 0xed, 0xc0, 0xfa, 0xd4, 0x83, 0xba, 0xcd, 0x0d, 0x80, 0x84, 0x8e, 0xc2, 0x88, 0x1a,
	0x97, 0x6e, 0xa3, 0x4e, 0x93, 0xb0, 0xde, 0x9b, 0xc2, 0xc4, 0x90, 0xd4, 0x06, 0xb0, 0x35, 0x93,
	0x8a, 0x72, 0xb4, 0x03, 0x25, 0xb5, 0x1b, 0x2d, 0x57, 0xdf, 0xe7, 0xe9, 0x7b, 0x26, 0x48, 0xe1,
	0xdf, 0x83, 0x7c, 0x6d, 0xc1, 0x85, 0x33, 0x51, 0xc4, 0xbf, 0x44, 0xb9, 0xd3, 0x39, 0x56, 0xcc,
	0x4b, 0x41, 0x34, 0x87, 0x2f, 0xc1, 0xaa, 0xba, 0x57, 0xd5, 0x25, 0xb9, 0x94, 0x65, 0xa5, 0x0a,
	0x04, 0x46, 0x34, 0x25, 0x44, 0x31, 0x1f, 0x32, 0x2e, 0x66, 0x66, 0x88, 0xba, 0x02, 0x23, 0x9a,
	0x12, 0x9f, 0x80, 0xb1, 0x71, 0x9e, 0x56, 0xf4, 0x27, 0x60, 0xee, 0x3c, 0x99, 0xaa, 0xda, 0x47,
	0x50, 0x31, 0xf7, 0x1f, 0x6f, 0xc0, 0x8a, 0xf8, 0x07, 0xe4, 0xb3, 0xd1, 0x81, 0xa4, 0x84, 0x28,
	0x06, 0x5f, 0x85, 0x12, 0x1d, 0x0c, 0xe2, 0x49, 0x34, 0xbd, 0x49, 0x17, 0x94, 0xca, 0x51, 0x28,
	0x99, 0xd2, 0x37, 0x5f, 0x2c, 0x43, 0xd9, 0xf8, 0xbe, 0x62, 0x05, 0x4a, 0xbe, 0x17, 0xf4, 0x83,
	0x56, 0xdb, 0xb3, 0xff, 0x87, 0x36, 0x54, 0x1c, 0xf7, 0x43, 0xa7, 0xd3, 0xf4, 0x14, 0x62, 0x21,
	0xc2, 0x7a, 0xdb, 0x21, 0x1f, 0x78, 0x41, 0xdf, 0xdf, 0x6f, 0xb7, 0x1d, 0x72, 0x60, 0x17, 0xb0,
	0x0c, 0xc5, 0xfc, 0xb1, 0x24, 0x4c, 0xfc, 0xfd, 0x07, 0xed, 0x56, 0xd0, 0xef, 0x12, 0xd7, 0x23,
	0xf6, 0x50, 0x20, 0x4d, 0xe1, 0xe2, 0xb1, 0x46, 0x18, 0x6e, 0x40, 0xd9, 0x69, 0x7b, 0x1d, 0x57,
	0x03, 0x87, 0x78, 0x05, 0xb6, 0x3b, 0xdd, 0xa0, 0xf5, 0xf0, 0xa0, 0x1f, 0x10, 0xc7, 0xf5, 0x48,
	0xdf, 0x69, 0x36, 0xbb, 0xfb, 0x9d, 0xc0, 0x1e, 0x89, 0x84, 0x9e, 0xb4, 0x82, 0x47, 0x2e, 0x71,
	0x9e, 0xd8, 0xcf, 0x70, 0x1b, 0x6c, 0x69, 0xe3, 0xf7, 0x1f, 0x1c, 0xf4, 0x55, 0x22, 0xf6, 0xb7,
	0x16, 0x6e, 0xc1, 0xc6, 0x29, 0xdc, 0x73, 0x48, 0x70, 0x60, 0x7f, 0x67, 0xe1, 0x55, 0xb8, 0x24,
	0xd1, 0x53, 0x6d, 0xdf, 0xe9, 0xb8, 0xfd, 0x96, 0x6b, 0x7f, 0x6f, 0xe1, 0x65, 0xc0, 0x29, 0x49,
	0xbc, 0x87, 0x1e, 0xf1, 0x3a, 0x4d, 0xcf, 0xfe, 0xc1, 0xc2, 0x4d, 0xa8, 0x68, 0xf1, 0x83, 0x03,
	0xa1, 0xfd, 0xd1, 0xc2, 0x0a, 0x14, 0x15, 0xe4, 0xdb, 0x3f, 0x99, 0x02, 0xd7, 0xeb, 0x05, 0x8f,
	0xec, 0x9f, 0x2d, 0xdc, 0x00, 0x78, 0xec, 0xf8, 0x81, 0xca, 0xde, 0xfe, 0xc5, 0x42, 0x1b, 0xca,
	0x32, 0x0d, 0xed, 0xe3, 0x85, 0xf4, 0x21, 0x90, 0x96, 0xe7, 0xdb, 0xbf, 0x5a, 0xa2, 0x0e, 0xa9,
	0x35, 0xeb, 0xf8, 0x4d, 0xd6, 0x71, 0x0a, 0xab, 0x3a, 0x7e, 0x9f, 0x41, 0x55, 0xcb, 0xfe, 0x90,
	0x05, 0xf4, 0xba, 0x7e, 0x2b, 0x68, 0x75, 0x3b, 0x86, 0xfc, 0x4f, 0x19, 0xa9, 0xe9, 0x74, 0xdc,
	0xc7, 0x9e, 0x6f, 0xff, 0x65, 0xe1, 0x25, 0xd8, 0xd4, 0xcd, 0x34, 0x54, 0x9f, 0x16, 0xf0, 0x06,
	0x5c, 0x9b, 0xc3, 0x65, 0x7b, 0x74, 0x36, 0x9f, 0x15, 0xf0, 0x3a, 0xec, 0x2c, 0x96, 0x04, 0x07,
	0x3d, 0xcf, 0xfe, 0xbc, 0x80, 0xbb, 0x70, 0x75, 0xb1, 0xc0, 0xf1, 0x7d, 0x2f, 0xb0, 0xbf, 0x28,
	0x3c, 0x5d, 0x95, 0xd7, 0xef, 0xfe, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xdc, 0x7c, 0x45, 0x65,
	0xeb, 0x0a, 0x00, 0x00,
}
